### ISSUE TITLE
Consider un-sealing the Subject set of classes

### ISSUE THREAD

**Issue by raffaeler** [dotnet/reactive#1023]
The use case I faced is when you want to register Subject<T> as a service in a DI.
Let's say for example that I want to use a Subject<T> to publish events (T) from a service and a second Subject to receive the same set of events (T) from another service.

Since Subject can't be derived, I cannot register more than one Subject<T> in the DI.
There are workarounds, but they are annoying:
- wrapping Subject<T>
- using different interfaces for 'T' even if the set of events are exactly the same

Thoughts?

**Comment by akarnokd** [comment]
> register Subject as a service in a DI

I'm not familiar with "service in a DI", what does that mean?

> There are workarounds, but they are annoying: wrapping Subject

Assuming you use an `ISubject<T>` type as a key in a dictionary then yes. There is no good way to subclass a subject even if it was allowed. The multicasting behavior can't be reasonably opened up for customization.

**Comment by raffaeler** [comment]
DI = Dependency Injection
It is getting more and more popular since ASP.NET Core provided it in the box, but can also be used in other contexts, including desktop apps.

When you want to provide a subject via DI, typically DI frameworks ask you to register an instance of your service like this:
```
services.RegisterSingleton<IMyService, MyService>();
```
This basically is asking the DI framework to create an instance of MyService and provide that instance to all the other services requiring it in the parameter list of their constructor. You can ask to the DI any service that has been registered in the DI.

If I can't derive the subject class, I can't differentiate more than one subject. For example in an IoT application I can have two different Subject<Temperature>, another Subject<Humidity> (and more).
I need a different type, not to override the methods, but just because I need a different Type that is used from the DI to understand which service should be plugged in.
Also, if not sealed, I can make my "custom subject" derive my own "IExternalTemperature" which can even be empty and is used to "tag" the service for external temperatures.

So, no need to "subclass" in terms of  methods, but just the need to derive it to have a new type name and avoid cumbersome workarounds.

**Comment by akarnokd** [comment]
I see. As I mentioned, subclassing a subject can't be done reasonably thus if it was allowed, that could open up a lot of trouble for other use cases. Perhaps @bartdesmet can weigh in on the topic.

You could, of course, take the subject implementations by source and not have it sealed in your own project.

**Comment by raffaeler** [comment]
Forking the code for this reason is way too "expensive".
I can wrap the Subject<T> in a factory, it is doable but definitely annoying and I believe it could obstacle people not very familiar with DI in general.

We have seen that, althought RX are awesome, their adoption has not widened for many small details. I wish this one is not an additional one :)

**Comment by eugbaranov** [comment]
But why would you expose "naked" `ISubject<T>`?
Surely it is an implementation detail of your `IExternalTemperature` and as such should be encapsulated.

**Comment by raffaeler** [comment]
I would not call an implementation detail, just a well-known contract used to talk among objects.
The point is having an object leveraging the power of Subject<T> without implementing directly ISubject<T> (which is quite a long work), while also inheriting my own interface which is used to interact decently with the DI.
As a minimum, level my interface would be empty, just for the purpose to distinguish different objects. But I could also add more stuff (like name, description and other things).
Sealing the Subject<T> is limitating this scenario. Not saying there are no workarounds, there is just a lot of additional work to do.

**Comment by tekr** [comment]
If you really want to go down that route, you could use a DI container that supports named registrations (e.g. Autofac).

**Comment by aayjaychan** [comment]
I recently ran into a similar scenario where I want to resolve `IObservable<T>` from the DI container.

I usually avoid clients from having access to both `IObservable<T>` and `IObserver<T>`, so I rarely expose `ISubject<T>` directly, but let's use `ISubject<T>` in the following examples.

To integrate `ISubject<T>` with a DI framework, we can use one of two patterns: the composite pattern and the delegation pattern. Both patterns hold a `Subject<T>` that does the heavy lifting.

Composite pattern just expose the subject as a property. Similar to a factory, but less ceremony:
```
public interface IExternalTemperature
{
    public ISubject<decimal> Readings { get; }
}

public sealed class MyExternalTemperature : IExternalTemperature, IDisposable
{
    private readonly Subject<decimal> _subject = new Subject<decimal>();

    public ISubject<decimal> Readings => _subject;

    public void Dispose() => _subject.Dispose();
}
```

In the delegation pattern, we inherit `ISubject<T>` in the service interface, and the implementation just forwards method calls:
```
public interface IExternalTemperature : ISubject<decimal>
{
}

public sealed class MyExternalTemperature : IExternalTemperature
{
    private readonly Subject<decimal> _subject = new Subject<decimal>();

    public void OnCompleted() => _subject.OnCompleted();

    public void OnError(Exception error) => _subject.OnError(error);

    public void OnNext(decimal value) => _subject.OnNext(value);

    public IDisposable Subscribe(IObserver<decimal> observer) =>
        _subject.Subscribe(observer);
}
```

In both cases, we can just register and resolve `IExternalTemperature`.

I usually use the composite pattern because it requires less code on the service and provides better separation of concerns, but `ISubject<T>` has four methods only, so delegating is not too much work either.

**Comment by bartdesmet** [comment]
I do agree with @akarnokd's assessment, which aligns with the design decisions on subject types. These types are intentionally marked as `sealed` because there's no meaningful extensibility point (i.e. `virtual` methods, including those indirectly added via base classes, in this case `SubjectBase<T>` and `Object`) due to the inherent complexity around locks and synchronization. The primary decision point with regards to "to seal or not to seal" is around (designing for enabling) extensibility, with the slight added bonus that JITted code can (ever so slightly) be faster in the case of `sealed` types.

At this point, I don't think the use of some DI technology carries enough weight to significantly influence the decision making around `sealed` types. Just deriving from a type such that `GetType()` returns another value seems like working around an issue of the lack of being able to tag instances.

So, with all of this in mind, I'm of the opinion that (selective) delegation/composition wins over inheritance, as shown in the sample by @aayjaychan.
