### ISSUE TITLE
Integration with Fody.Costura

### ISSUE THREAD

**Issue by Logerfo** [dotnet/reactive#1042]
Is there some known successful Reactive integration with [Fody.Costura](https://github.com/Fody/Costura)? I'm currently having some issues, but I had never seen this before:
> System.BadImageFormatException: Could not load file or assembly 'System.Linq.Async, Version=4.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. Reference assemblies should not be loaded for execution. They can only be loaded in the Reflection-only loader context. (0x80131058)

Thank you.

**Comment by onovotny** [comment]
I would raise an issue with Fody. Ix uses ref assemblies and lib for implementation. They could be loading the wrong thing.

**Comment by Logerfo** [comment]
Well, since I'm testing a still non production comercial code, I'm not a "patron" yet, so I cannot open any issues. I'm not requesting the reactive team to investigate this, only asking if there is any successful integration that I could use as an example.

**Comment by onovotny** [comment]
I'm not aware of any integration. Based on your description, it appears to be a bug in Fody in that it's choosing the ref assembly to embed rather than one of the lib ones. I'm not sure how Fody can handle this as there can be different libs based on the target -- ie, if you're on windows and using wpf/winforms, you get a different impl than if you are not. This works transitively in NuGet, I'm not sure how Fody would go about embedding all of this.

**Comment by SimonCropp** [comment]
given the current plan is to Sunset/Obsolete Costura https://github.com/Fody/Costura/issues/442 i doubt this will get much priority

**Comment by SimonCropp** [comment]
update: i am going to pull the trigger on obsoleting Costura. so suggest this issue be closed
