### ISSUE TITLE
Excessive unmanaged memory usage when creating delayed observables

### ISSUE THREAD

**Issue by Quodnon** [dotnet/reactive#1047]
Hi, guys. 
I've faced an issue of excessive unmanaged memory growth when I used` Observable.Delay()` and `Observable.Switch().` The example code is [here](https://gist.github.com/Quodnon/1ce85baba06fc3570ffbf7bcb99a3be8#file-testhighamountofunmanagedmemory-cs-L71) or here https://github.com/Quodnon/LeackyRxDelay.
The use case is following:
We have a stream of entities and we want to check if at some point in time particular entity got to a certain state. The approach is to apply `groupByUntil()` onto the subject and then delay entities by certain time. And in order to get the last state of the sequence I use `Switch()` operator.
Is it the use case for RX and are there any workarounds?

**Comment by akarnokd** [comment]
Which version are you using?

Do you have objects that have unmanaged components (not apparent in the example to me)? I.e., `Return(x)` where `x` references a file handle or whatnot? 

If you have to deal with resources associated with a flow, `using` is the way to scope them to the flow's lifecycle so that flow cancellation can clean them up. This unfortunately can mean having `using` around each element provided via `Return`.

**Comment by Quodnon** [comment]
Well, the console in example above doesn't have third-party components. 
I see that when i create subject
```csharp
class TestEntity
    {
        public TimeSpan DelayTime { get; set; }
        public string Id { get; set; }
        public string UpdateData { get; set; }
    }
//then in code
var subj = new Subject<TestEntity>();
var testSubj = subj.GroupByUntil(x => x.Id, x => x.Select(y => y.UpdateData == "removed"))
                   .SelectMany(group =>
                    group.Select(e =>
                    {
                        return Observable.Return(e).Delay(e.DelayTime); 
                    }).Switch())
                .Where(x => x.UpdateData == "filtered")
                .Select(x => x);
```

and later send `N` messages with id 1 to that subject i will create `N` delayed  observables. Because of `Switch()` i will take the last one message.
The question is then can i somehow dispose the delayed observable from previous messages?

**Comment by akarnokd** [comment]
`Switch` should dispose the older `Observable`s by design. With a 3rd party operator such as [`DoOnDispose`](https://github.com/akarnokd/reactive-extensions#doondispose) you should be able to intercept and print such disposes.

**Comment by akarnokd** [comment]
The `_queue` should get GCd because a dispose should disconnect the operator, however, the `_queue` is unaware what data it hosts.

What unmanaged memory is associated with the object you are using? Perhaps you need to work out the finalization for the wrapper object.

**Comment by Quodnon** [comment]
I don't see any unmanaged object data related to `T` of my `Subject`. I've made a console project for test and would much appreciate any comments https://github.com/Quodnon/LeackyRxDelay

**Comment by bartdesmet** [comment]
The problem is with the default scheduling behavior around the `ISchedulerLongRunning` optimization, which results in the creation of separate threads in `Delay`. In this case, we have 25,000 instances of `Delay`, each of them creating a thread:

```
> get-process ConsoleApp* | select { $_.Threads.Count }

 $_.Threads.Count
------------------
             25011
```

That's where the native memory comes from. The "optimization" clearly works against this scenario and is meant for having few `Delay` operators with high message volumes. In this case, it's completely the opposite with tons of `Delay` operators to delay a single message by minutes.

The stacks of these threads look like:

```
0d 00000077`0fbfe6f0 00007ff9`755e626a System_Private_CoreLib!System.Threading.ManualResetEventSlim.Wait(Int32, System.Threading.CancellationToken)+0x265
0e 00000077`0fbfe790 00007ff9`758d0acc System_Reactive!System.Reactive.Linq.ObservableImpl.Delay`1+Base`1+L[[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]].DrainQueue(System.Reactive.Disposables.ICancelable)+0x37a*** ERROR: Module load completed but symbols could not be loaded for d:\temp\LeackyRxDelay\bin\Debug\netcoreapp3.0\System.Reactive.dll
```

where the `L` in the type name indicates it's using the `ISchedulerLongRunning` optimization. It sits right here:

https://github.com/dotnet/reactive/blob/a39262b0de0292cd9a258105f0559ddfdbdfc27e/Rx.NET/Source/src/System.Reactive/Linq/Observable/Delay.cs#L341

Unfortunately, operators can't predict the usage pattern (how many of them, and event rate), so strategies such as "long running" operators work well for one case (which we deemed to be the common case), but not for the other. Prior to this, every delayed *event* resulted in a bunch of allocations and timeliness of the delay was a problem for high-volume event streams, which was what we were dealing with in the Rx v2.x days (for system monitoring systems etc.). That's where these optimizations came from.

The good news is that we have means to disable these optimizations for cases where it hurts:

```csharp
     return Observable.Return(e)
       .DoOnDispose(() => { disposePreDelayCount++; }) //works well
       .Delay(e.DelayTime, Scheduler.Default.DisableOptimizations())
```

where `DisableOptimizations` is an extension method in `System.Reactive.Concurrency`. You can be more selective as well:

```csharp
     return Observable.Return(e)
       .DoOnDispose(() => { disposePreDelayCount++; }) //works well
       .Delay(e.DelayTime, Scheduler.Default.DisableOptimizations(typeof(ISchedulerLongRunning)))
```

With these changes, it reports:

```
> get-process ConsoleApp* | select { $_.Threads.Count }

 $_.Threads.Count
------------------
                11
```

There's still a question as to why these threads didn't quit when `Dispose` is called on the `Delay` operator's subscription. I can have a look at that later if I have some spare cycles.

**Comment by bartdesmet** [comment]
Actually, the use of `DoOnDispose` is misleading here:

```csharp
     return Observable.Return(e)
       .DoOnDispose(() => { disposePreDelayCount++; }) //works well
       .Delay(e.DelayTime);  //still generates tons of unmanaged memory
```

I definitely to expect the number to add up to 25,000 simply because `Return` will send `OnCompleted` down, which flows through `DoOnDispose` into `Delay`, which then will dispose its source subscription, thus making `DoOnDispose` action run. We're not measuring whether the `Delay` gets disposed here. If we add:

```csharp
     return Observable.Return(e)
       .DoOnDispose(() => { disposePreDelayCount++; })
       .Delay(e.DelayTime)
       .DoOnDispose(() => { disposePostDelayCount++; });
```

We see that `disposePostDelayCount` is `0`, so the `Delay` instances are alive, which explains why the threads are still alive (or, when disabling the optimization, why related managed objects will still be alive).

If I add logging to the output of `GroupByUntil`:

```csharp
subj.GroupByUntil(x => x.Id, x => x.Select(y => y.UpdateData == "removed"))
  .Do(g => { groupCount++; })
```

I see that 25,000 groups are created. So we got 25,000 groups, each emitting a single event. Each group has an active `Switch` in charge of delaying the group's single event. So I do expect everything to be alive.

Simple repro with a narrative:

```csharp
var s = new Subject<int>();

var d = s.Select(x => Observable.Return(x).DoOnDispose(() => Console.WriteLine("Before")).Delay(TimeSpan.FromSeconds(10)).DoOnDispose(() => Console.WriteLine("After"))).Switch().Subscribe(Console.WriteLine);

// Creates the first and only inner sequence, i.e. Return(1), which will emit OnNext(1) and OnCompleted().
// Delay will properly delay the OnCompleted() message for 10 seconds.
// We'll see "Before" being printed. The OnCompleted() message received by Delay from Return will boomerang back to Dispose the source of Delay.
s.OnNext(1);

// Switch will receive OnCompleted, but there's an active inner source, i.e. Return(1).Delay(10s), so that source is responsible to emit On*. This is pretty much a no-op now. Return(1).Delay(10s) is the boss.
s.OnCompleted();

// By here, we will only have seen "Before". If we wait 10 seconds, we'll see "1" being printed, followed by "After".
Console.ReadLine();

// Or if we continue directly and proceed to Dispose the whole subscription, it also prints "After".
d.Dispose();
```

So it's merely a matter of picking your poison for the scheduler configuration of `Delay`, as discussed above. All behavior is by design.

**Comment by Quodnon** [comment]
thanks guys
