### ISSUE TITLE
Where is Window operator for IAsyncEnumerable?

### ISSUE THREAD

**Issue by 3da** [dotnet/reactive#1075]

**Comment by akarnokd** [comment]
It was never implemented. Do you have a specific use case for it?

**Comment by 3da** [comment]
Nope, just saw this operator and wonder how it is funny

**Comment by marco6** [comment]
Can we actually re-open this? It would be very beneficial to have such an operator. A typical example would be grouping notifications.

For example, we are using WebSockets to notify our GUI. We have many small updates, so we want to group them and send a single message which contains all the notification in that period of time instead of a message per update. Right now we are forced to have an IObservable, window over it, call ToAsyncEnumerable for it, and all of its items. This forces us to keep a dependency on System.Reactive and it has threading (and performance) implications.
