### ISSUE TITLE
CombineLatest for IObservable<IObservable<TSource>>

### ISSUE THREAD

**Issue by Jason-Enderby** [dotnet/reactive#1143]
#### Feature request

> Which next library version - major

> What are the platform(s), environment(s) and related component version(s)? - Software can be upgraded as needed

> How commonly is this feature needed - Several projects

Concat & Merge both have overrides that can operate on IObservable<IObservable<TSource>>.
This is great, but a use case I keep running into is wanting the last values of each group within a GroupedObservable.

This could be implemented as an extension method similar to that of below:

```cs
public IObservable<IList<TSource>> CombineLatest<TSource>(IObservable<IObservable<TSource>> sources)
{
 return outer
    .Scan(new List<IObservable<T>>(), (list, ob) => list.Concat(new[] {ob}).ToList())
    .Select(list => list.CombineLatest())
    .Switch();
}
```

However, I feel that this feature would be a logical extension to the core api.
I do however understand that this could lead to memory management problems when dealing with an outer observable that is chatty.

```cs
sourceObserable
  .GroupBy(s => s.Id)
  .CombineLatest()
  .Subscribe(latestItems => {
    // Process latest item from each Id grouping
  });
```

**Comment by Jason-Enderby** [comment]
Is this something that could be added to `QueryLanguageEx`

I will happily implement a pull request if this feature is deemed appropriate.

**Comment by akarnokd** [comment]
It is trivial to aggregate observable into a list and then apply `combineLatest` or `zip`, which require a known and fixed number of sources to work. I don't think such overloads should be in Rx.NET proper but you can have it in your project.

**Comment by Jason-Enderby** [comment]
You could say the same for Merge.
 You could aggregate the outer observable into a list of observables and then call the IList<IObservable<TSource>> variant to get the same behavior. But in this case, you provide the override for IObservable<IObservable<TSource>> which is a lot more convenient.

**Comment by akarnokd** [comment]
Wrong. Merging an observable sequence of observables is a completely different operation with different semantics. Each inner observable can arrive over time and there could be any number of such inner observables being merged into a single stream over the lifetime of the outer observable, without them needing any item-based correlation.

CombineLatest operates by taking a full row of latest values available and transform them into one output value per row. For this, the number of sources have to be known, otherwise there is no way to know when a row can be considered full. It is very rare the number of sources to combine is not known when the subscription happens.

**Comment by Jason-Enderby** [comment]
I do recognize that Merge has the benefit of outputting a simpler type signature.
However, the idea here is to add the same concept  to combineLatest.
 The source is the same and has the same constraints `IObservable<IObservable<T>>`. That outer observable could produce a new inner observable at any time and there is no way of telling when that might happen.
 This is outputting outputting a list of length n + 1 wherever a new inner observable is emitted and an updated list wherever any of the inner observables emit. It's not waiting for the completion of the outer observable to complete before outputting. 


As a usage example. Say you have a stream of messages coming from multiple sources on a single stream, like a message bus topic. 
Each of these messages could come from a different source and contain an Id property.

Now say that you want a stream of the latest value from each of the services.
This means that you need to aggregate state in some way.

Note: the version of combine latest I'm referencing in that `Select` has the signature `IEnumerable<IObservable<T>> -> IObservable<T>`. I don't think it's much of a strech to want to extend that to monitor an outer observable.

**Comment by akarnokd** [comment]
Still wrong. Merge doesn't need multiple of the inner sources to have items produced in order to emit; they can go completely independently.

Also your `GroupBy` + `CombineLatest` example can't work. You collect up all groups, which at that point will no longer signal any more items because the `GroupBy` operator has completed all groups and the sequence of groups itself (otherwise, `ToList` would never complete and emit the list of groups to be selected over).

As for any kind of live, rolling array-combination, it is prone to all sorts of problems. For example, any lack of data from a fresh source can prevent forming a new row; or if the number of sources keeps growing indefinitely, leading to massive performance degradation due to constant need to copy a large array of latest values all the time.

In addition, in your example with the one group per Id case, why do you want to correlate different Id groups and possibly correlate an arbitrary number of such groups? Why would you want to combine every fresh item of a group with the latest item of all the other groups?

See also #149.

**Comment by Jason-Enderby** [comment]
`GroupBy` will emit a new observable whenever a new group appears. It does not need to consume the entire source stream, that's the cool thing about GroupBy.

I do agree with the notion that `CombineLatest` requires an item from each source, but this is a problem with `CombineLatest` in any use of it's setup. One option in this case would be to call `.Select(innerOb => innerOb.StartWith(<someValue>))`.

And I again do agree that any rolling array combination is prone to problems, especially when growing infinitely, so this is more of a niche operator in that regard. 

But do take into regard that the example above is to illustrate a concept. An append only linked list would solve the memory inefficiencies for instance. Another flaw in that design is that the `Scan` / `ToList` combined with `Select(CombineLatest)` will force a re-subscription to all inner observable's whenever the list changes as it goes through `Scan`. 
Ideally the code would be based off of an operator similar to Merge where the previous subscriptions are always left open.

**Comment by akarnokd** [comment]
It doesn't work. If you don't believe me, create a small project, create the operator and then write some tests to verify it behaves as you think it would.

**Comment by Jason-Enderby** [comment]
I have code like this in a running project. 
What is the thing that you don't think works here. 

`GroupBy` emits over time

Scan creates an `IObservable<IList<T>>` that will emit an updated list every time the outer observable. 

So you get `IObservable<IObservable<IList<T>>`

Then there is a mapping to `CombineLatest` so you get `IObservable<IObservable<IList<T>>`
Then you switch so that the latest CombineLatest is the only source consumed.

But again, the implementation is not important here as it can be optimised if it's built from the ground up.

**Comment by akarnokd** [comment]
`ToList` doesn't work and that `Scan` will create larger and larger pool of sources which have to be hot, otherwise every `CombineLatest` application will restart the sequences. If they are hot, you have a race condition between abandoning the previous subscriptions to start the new subscriptions, which could lead to lost signals on one or many of those sources. The general setup works only when you have groups from `GroupBy` and the whole switcharound can happen synchronously to it.

You presented use cases that are quite error prone in general and represent a very peculiar behavior, thus not suitable for Rx.NET proper. You can, of course create your own extension method in your own library and publish it with as you see fit.

**Comment by Jason-Enderby** [comment]
I'm okay with this implementation being error prone, it's a good distinction that messages within the inner observables could be lost during resubscription.
I regret putting forward the example code as I had only put it there as a discussion point to the concept of a high level operator for CombineLatest.
I do believe that an operator that could handle this behavior in a safe manner would be valuable. 

As stated in the request you linked, each high level operator should be evaluated individually. 
If the comminity does not agree with the utility of such an operator, then so be it.
