### ISSUE TITLE
Call is ambiguous between Queryable and AsyncEnumerable extensions

### ISSUE THREAD

**Issue by joshmouch** [dotnet/reactive#1183]
I have the latest version of Entity Framework Core 3.1 and a bunch of LINQ queries.

As soon as I add `System.Interactive.Async` to the project, I start getting a bunch of errors about ambiguity between extension methods on `DbSet<>` instances.

It seems like the compiler can't decide on whether to use `System.Linq.Queryable.Where` or `System.Linq.AsyncEnumerable.Where`.

How do I fix this?  As a work around, I can remove `System.Interactive.Async`, and change everything to static calls instead of extension methods, but this isn't great:

e.g. 
Instead of:
```
dbContext.EntitiesA.Where(...)
```
Change to:

```
Queryable.Where(dbContext.EntitiesA, ...)
```

**Comment by danielcweber** [comment]
Dup of #1057 ?

**Comment by joshmouch** [comment]
Yes. I also found https://github.com/dotnet/efcore/issues/18124
I'll close this since it's redundant.

**Comment by ffMathy** [comment]
@joshmouch well, the other issue was closed and marked as "external", so what gives?

**Comment by ffMathy** [comment]
Can we re-open this?

**Comment by danielcweber** [comment]
As far as I understand this issue, it's only resolvable by one library changing the namespace of its extensions (i.e. System.Linq). But once you take a dependency on another library that has equally named extensions in that namespace, you're stuck again. So we might make this a discussion of "who should change its namespace" and I guess System.Interactive.Async, through C# 8's async iterator feature has a better position than EF, but I don't think that discussion will lead to any breaking changes in a future version of either library.

@clairernovotny Should anybody from the EF team weigh in?

**Comment by ffMathy** [comment]
I'd love to hear @davidfowl's take on this too.

**Comment by thomaslevesque** [comment]
> I guess System.Interactive.Async, through C# 8's async iterator feature, has a better position than EF

I'm not sure about this. The Where, Select, etc. methods are not specific to EF. They've been in .NET for at least 12 years. I don't see them moving to another namespace just because of AsyncEnumerable...

What might make sense is to NOT implement `IAsyncEnumerable<T>` on `DbSet<T>`. As far as I can tell, there's almost no use case where it's useful. If you want to filter or project, you want to do it on `IQueryable<T>`, because it will be translated to SQL and the filtering or projection will be done by the database. Treating the DbSet as `IAsyncEnumerable<T>` means you're going to fetch everything from the database, then work on it in memory. Why would you want that?

**Comment by quinmars** [comment]
> Treating the DbSet as IAsyncEnumerable<T> means you're going to fetch everything from the database, then work on it in memory.

That's right. Best would be to implement [`IAsyncQueryable<T>`](https://github.com/dotnet/reactive/blob/master/Ix.NET/Source/System.Linq.Async.Queryable/System/Linq/IAsyncQueryable.cs) instead of `IAsyncEnumerable<T>`.
