### ISSUE TITLE
Generic for Exception type for OnError

### ISSUE THREAD

**Issue by unitrix0** [dotnet/reactive#1238]
I just thought it would be great if it would be possible to specify the Exception type that is passed to the `OnError` method. For example in a HTTP Post method that I use it would be possible to return the whole  result object in the Exception object:

```
public static IObservable<T> PostAsync<T>(this HttpClient client, string requestUri, object value)
{
    return Observable.Create<T,CustomException>(async observer =>
    {
        try
        {
            string json = JsonConvert.SerializeObject(value);
            var content = new StringContent(json, Encoding.UTF8, JsonMediaType);

            HttpResponseMessage result = await client.PostAsync(requestUri, content);
            if (result.IsSuccessStatusCode)
            {
                string resultContent = await result.Content.ReadAsStringAsync();
                var obj = JsonConvert.DeserializeObject<T>(resultContent);
                observer.OnNext(obj);
            }
            else
            {
                observer.OnError(new CustomException(result));
            }

            observer.OnCompleted();
        }
        catch (Exception ex)
        {
            observer.OnError(ex);
        }
    });
}
```

**Comment by bartdesmet** [comment]
We did have this in very early precursors to Rx (when things were still called `IEvent<>`), but it got unwieldy very quickly due to the additional generic parameters on types such as `IObserver<T>` and on query operator methods. The extra static typing is only worth it if it flows through the entire system, which has a contagious effect, so we abandoned the idea.
