### ISSUE TITLE
BehaviorSubject<T>: OnNext(value) potentially emits out of order leaving last OnNext(value) out of sync with actual.

### ISSUE THREAD

**Issue by electricessence** [dotnet/reactive#1243]
#### Potential Flaw

Because the notifications occur outside the `_gate` lock, a highly threaded situation may happen in this order:

1. Thread 1 calls `OnNext(1)` and acquires a lock.
2. Thread 2 calls `OnNext(2)` and is blocked until the lock is released.
3. Thread 1 updates the value and exits the lock.  The final value is `2`.
4. Thread 2 acquires a lock, updates the value and exits the lock.
5. Outside the lock, Thread 2 beats Thread 1 to the punch and signals to observers the the value is `2`.
6. Thread 1 signals to observers the value is `1`.

The observers received `2` then `1`.  But the value is `2`.

Give more threads, this could easily get even more out of sync.

I see this as a potential flaw since `BehaviorSubject<T>` is already using a lock to synchronize.

**Comment by bartdesmet** [comment]
Subjects aren't thread-safe on the observer side (by design). Multiple threads invoking `On*` methods concurrently can result in out-of-order observation of notifications by subscribers. This is the case for all subjects. E.g. `Subject<T>` uses CAS operations to manage the list of subscribers and two or more threads concurrently executing `OnNext(T)` will result in no ordering guarantee.

The lock in `BehaviorSubject<T>` is there to protect against concurrent execution of `Subscribe`, `Dispose`, and `On*` invocations. It should be safe to invoke these three sets of operations concurrently (e.g. a `Subscribe` taking place while an `OnNext` is ongoing, here ordered by means of the lock), but `On*` is inherently sequential (and it's the caller's responsibility to ensure this).

Some historical note may be warranted. Early beta versions of Rx made the subjects synchronize the `On*` calls, making them (very) slow even in the face of a well-behaved sender (i.e. sequential invocation of `On*` methods). This was particularly painful for operators like `Publish` (and by extensions the `Multicast` family) as well as higher-order sequence generators (`Window`, `GroupBy`) which use subjects internally but have a single well-behaved source. This situation was akin to "synchronized collections". In a later beta of Rx, we added `Fast*` variants of all subjects (the ones you see now).

By the time we released v1.0, we did away with the synchronized variants completely, and removed the `Fast*` prefix. This decision was based on the observation that concurrent invocation of `On*` methods on an observer (which is dual to concurrent invocation of `MoveNext` on an enumerator) is inherently unsafe. In fact, if you concurrently invoke `On*` on a `Subject<T>` and use code like this:

```csharp
xs.Take(1_000_000).Count().Subscribe(Console.WriteLine);
```

where `xs` is a subject being accessed concurrently, there's no guarantee you'll see `1000000` getting printed. The `Take` operator does not use interlocked operations, and this too is by design. Operators are built around the assumption that observer callbacks from a subscription to a source won't overlap (i.e. run concurrently). As such, we only need to synchronize in operators that deal with more than one source.

Even though we changed the default for subjects to be non-synchronizing on the observer side, we provided a "cure" by means of the `Observer.Synchronize` method which can be used to synchronize `On*` calls in a pay-for-play manner. None of the operators use this; it's solely there for cases where you have an `IObserver<T>` and want to safely publish it to multiple threads that may cause concurrent invocations of `On*` methods.

**Comment by electricessence** [comment]
Ok.  Which observable extension could I use to guarantee synchronization and order?

**Comment by bartdesmet** [comment]
The root of the problem in this case is concurrent calls on the subject's On* methods. Either synchronize these manually (e.g. guarantee a single thread, use a lock, etc.), or wrap the subject using Observer.Synchronize, and make the calls on the resulting IObserver<T> instead.

See https://github.com/dotnet/reactive/blob/8172a2306fd50c9ea8cd097638cbf5f9f74cdbb9/Rx.NET/Source/src/System.Reactive/Observer.Extensions.cs#L194.

**Comment by electricessence** [comment]
@bartdesmet Thanks.  This helps.
