### ISSUE TITLE
[Discussion] Alternative IAsyncObservable definition.

### ISSUE THREAD

**Issue by quinmars** [dotnet/reactive#1296]
Some while ago, @bartdesmet mentioned that after the release of the `IAsyncEnumerable` interface and contract, the `IAsyncObservable` implementation will be reviewed. At that time there were some open question how the interface will evolve: will it support batch processing, will it use `Task` or `ValueTask`, will it support concurrent cancellation? Now that the `IAsyncEnumerable` interface is part of the BCL, it is a good point, to see how the `IAsyncObservable` can be aligned to its enumerable counter-part. I will propose an alternative `IAsyncObservable` definition later. 

First let me give you a short, selected feature list of `IAsyncEnumerable`, which the current `IAsyncObservable` is lacking at least partially. It supports:

 - concurrent upstream cancellation via `CancellationToken`
 - exceptionless in-stream cancellation via `break` in the `foreach` loop
 - exceptional cancellation via `throw`
 - sequential, asynchronous disposal of resources (the `IDisposeAsync` may only be called during `MoveNextAsync`)

As you may have noticed, I'm stressing here several kinds of cancellation. Cancellation is one of the toughest points of the synchronous Rx. And it tooked me months to understand why (synchronous) in-stream cancellation is not possible and therefore operators like `Take` cannot work how one would naivily expect. The current `IAsyncObservable` inherits those problems, because it is an one-to-one translation of its synchronous counterpart.

Take for example the following example, a poor man's implementation of a timer:

```csharp
Task<IDisposable> t = AsyncObservable
	.Range(0, 10)
	.Select(_ => await Task.Delay(1000))
	.SubscribeAsync(observer);
 var disposable = await t;
```

Awaiting the task `t` will take roughly 10 seconds. At the end you get an `IDisposable` with that you could cancel the already finished sequence. But why should I wait 10 seconds to get something that is worthless?

There are three reason why one may want to await a task:
 
  1. To get its value.
  2. To get the time point when it is completed.
  3. To get the exception that stopped the task to complete successfully. 
  
Exceptions are propagated downstream, so we can scratch item 3. In the example above we could use it for point 2. But there is a dedicated method in the observer just therefore. We all know that we have to use some scheduler to retrieve the `IDisposable` before the sequence is already finished, but what is the meaning of the awaited time there?

The `IAsyncEnumerable` uses a cancelation token to cancel an on-going sequence. With that we could write:

```csharp
Task t = AsyncObservable
	.Range(0, 10)
	.Select(_ => await Task.Delay(1000))
 	.SubscribeAsync(observer, token);
await t;
```

Now cancellation can be done at any time. Even before we subscribe. So why should we await here the task `t`?
I propse to get the completion of the sequence, may it be successful or exceptional.
 
The interface of the observable would then be:
 
```csharp
public interface IAsyncObservable<out T>
{
	ValueTask SubscribeAsync(IAsyncObserver<T> observer, CancellationToken token);
}
```

Since we already get the completion and the potential errors with awaiting the subscription task, the observer interface can be very thin:

```csharp
public interface IAsyncObserver<in T> : IAsyncDisposable
{
	ValueTask<bool> OnNextAsync(T value);
}
```

As expected there is a method to push items downstream. The return value is similar to the return value of `MoveNext`, but here it is the consumer that signals that it do not want to receive more values. That is compare able to the `break` keyword in the `IAsyncEnumerable` case. The next value may not be pushed before the previous task completed. There is no `OnComplete` nor an `OnError` method for the observer. If an operator needs to know if a sequence stopped successfully or exceptional it needs to await the subscription task. Once a sequence ends (sucessfully or exceptionally), the observer is disposed by the source. Here the same rules apply like for the `IAsyncEnumerable` interface. The `DisposeAsync` method may not be called before the last call to `OnNextAsync` completed including the returned task.

The contract for a forward operator, i.e., `IAsyncObservable -> IAsyncObservable` like 'Select', 'Where', 'Skip', etc.)

 - If an observer throws an exception on `OnNextAsync` it is ok to pass-through this exception.
 - If some user code, like for example a selector, throws an exception it is ok to throw this exception on the `OnNextAsync` callee.
 - It is ok to pass-through the cancellation token. It is not required to directly check for cancellation.
 - If an operator initiates a (long) running task, but returns a completed task, it can await the on going task in the `DisposeAsync` call. Examples would be `Throttle`, `Sample`, `Prefetch`, etc.

A combining operator has to handle exceptions and cancellation differently. The operator has to catch an exception to then cancel the subscriptions of the sources. Hence it needs a `CancellationTokenSource` on its own.

I already played around with this design in my repo https://github.com/quinmars/AsyncObservable2. I know that the upstream flow of exceptions and completion breaks with Rx traditions and may be controversial, but it makes exception handling much easier, in many cases exceptions do not need to be handled at all, because they can be passed through.

**Comment by bartdesmet** [comment]
Changes with ValueTask rather than Task are planned, across the board. Addition of cancellation support on selectors, predicates, etc. too. All of this in support of being analogous to IAsyncEnumerable and the System.Linq.Async operator surface.

This said, there are no plans to deviate from the flow of notifications for the three channels, in support of remaining analogous to Rx and dual to IAsyncEnumerable. I.e. IAsyncEnumerator<T> is really a Func<Task<Notification<T>>> (that is, MoveNextAsync codifies asynchronously returning any of three possible results) while IAsyncObserver<T> is a Func<Notification<T>, Task> (that is, On*Async codifies asynchronously providing any of three possible results).

The exact form of cancellation being provided top-level is still under consideration, in particular the dual of GetAsyncEnumerator taking in a CancellationToken. Current thinking is that most observers have a token as part of their state to pass down to e.g. async selectors and predicates with cancellation support. That matches the idea that observers are "hot" and stateful. As such, AsyncObserver methods (new in Async Rx compared to classic Rx, using an approach of "lifting" observable algebra over observer algebra) would likely take CancellationToken parameters. This is analogous to async iterators in C# supporting a cancellation token that binds to GetAsyncEnumerator.

(Typed on phone. More to follow later.)
