### ISSUE TITLE
ForEachAsync vs ForEachAwaitAsync

### ISSUE THREAD

**Issue by johnknoop** [dotnet/reactive#1404]
#### Question

Hi! Is there any functional difference between these two extension methods?

```cs
public static Task ForEachAsync<TSource>(this IAsyncEnumerable<TSource> source, Action<TSource> action, CancellationToken cancellationToken = default);

public static Task ForEachAwaitAsync<TSource>(this IAsyncEnumerable<TSource> source, Func<TSource, Task> action, CancellationToken cancellationToken = default);
```
I've tried googling "ForEachAsync vs ForEachAwaitAsync" but couldn't find any material describing them.

Both methods seem to fit statically:

```csharp
await myList.ToAsyncEnumerable().ForEachAsync(async element =>
{
	await DoSomethingWith(element);
});

await myList.ToAsyncEnumerable().ForEachAwaitAsync(async element =>
{
	await DoSomethingWith(element);
});
```
Is there any difference in how they will be awaited?

**Comment by danielcweber** [comment]
[Digging into the sources](https://github.com/dotnet/reactive/blob/main/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncEnumerable.AsyncOverloads.cs#L32) I'd say yes, they're equivalent. ForEachAwaitAsync just accounts for consistent naming across operators that take async functions as parameters etc.

**Comment by johnknoop** [comment]
@danielcweber thanks for the clarification.

**Comment by bartdesmet** [comment]
The first overload is not meant to be used with an async function for the `Acton<TSource> parameter:

```csharp
public static Task ForEachAsync<TSource>(this IAsyncEnumerable<TSource> source, Action<TSource> action, CancellationToken cancellationToken = default);
```

The thing that's "wrong" about it such usage is that the use of an `async` lambda results in an `async void` function that we can't await, and hence we'll end up with fire-and-forget async for the actions invoked for each of the elements (and those could then run concurrently, so you don't really get the equivalent of `await foreach`).

(Ideally, we'd have a Roslyn analyzer that warns against this usage.)

But besides that, @danielcweber is right to point out that the goal of the `Await` word in there was to make the intent clear and the APIs consistent, though the verbosity is unfortunate. This all originated from operators like `Select` where you could legitimately want to project a `T` onto a `Task<R>`, and get a sequence of `Task<R>` objects, rather than awaiting them to get a sequence of `R` objects. So we have `Select` which just projects (using a `Func<T, R>` where `R` may happen to be a `Task<U>` object) and `SelectAwait` which invokes the selector function and awaits the (value) task returned by the selector function to produce a value.

In the case of `ForEachAwaitAsync` it's `Async` because it returns a task-like type (so you await it, which means awaiting the completion of the entire iteration), and it's `Await` because the action is awaited for each iteration.

Finally, note the comment I left in the code over here: https://github.com/dotnet/reactive/blob/main/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ForEach.cs#L15

```csharp
        // REVIEW: Once we have C# 8.0 language support, we may want to do away with these methods. An open question is how to
        //         provide support for cancellation, which could be offered through WithCancellation on the source. If we still
        //         want to keep these methods, they may be a candidate for System.Interactive.Async if we consider them to be
        //         non-standard (i.e. IEnumerable<T> doesn't have a ForEach extension method either).
```

The `Action<T>`-based overload is a remnant from the days before C# 8.0 where we didn't have `await foreach` yet, nor a final story on cancellation (which we now have with `WithCancellation` in the .NET libraries). Unfortunately, the ship sailed with these overloads even after C# 8.0 shipped, so we never got around to removing them. Taking them away would be a breaking change, but we can make things better by detecting use cases like:

```csharp
await myList.ToAsyncEnumerable().ForEachAsync(async element =>
{
	await DoSomethingWith(element);
});
```

in a Roslyn analyzer (which could be more general than this particular case; all uses of binding an async lambda to a `void`-returning delegate type are often questionable, no matter whether it's for `System.Linq.Async` or some other function).

**Comment by bartdesmet** [comment]
Linking https://github.com/dotnet/reactive/issues/1397.

**Comment by johnknoop** [comment]
@bartdesmet 

I think I included the wrong overload in my first message. This is the one I mean:

```cs
public static Task ForEachAsync<TSource>(this IAsyncEnumerable<TSource> source, Func<TSource, Task> action, CancellationToken cancellationToken = default) => ForEachAwaitAsyncCore<TSource>(source, action, cancellationToken);
```

**Comment by bartdesmet** [comment]
That overload is a compatibility thing indeed, predating the `Await` nomenclature and allowing existing users of Async Ix (predating the work on support async on all callbacks, leading to the ambiguity described above) to upgrade without incurring major pain. At best, we could consider deprecating these old compatibility "aliases" to urge people to move to the (unfortunately more verbose, but non-ambiguous and universally consistent) variants.

Hope this helps and sorry for the possible confusion this may have caused; it's the price to pay for having a library that goes back for over 7 years (when we prototyped `IAsyncEnumerable<T>` as a sibling to Rx), and then adjusting it to work with `IAsyncEnumerable<T>` once it was finally adopted (albeit with some great improvements applied to it) in .NET several years later, while providing a smooth path for existing users to migrate. The cost of compat :-).

**Comment by johnknoop** [comment]
Got it. Thanks!
