### ISSUE TITLE
Website reactivex.io is not using https

### ISSUE THREAD

**Issue by AtosNicoS** [dotnet/reactive#1500]
It should be easy for a company like microsoft to enable https here:
http://reactivex.io/

**Comment by quinmars** [comment]
I don't think that domain is owned by Microsoft.

**Comment by akarnokd** [comment]
That site is backed by https://github.com/ReactiveX/reactivex.github.io and I don't know who owns the domain:

[ ] Enforce HTTPS — Unavailable for your site because your domain is not properly configured to support HTTPS

https://docs.github.com/en/github/working-with-github-pages/troubleshooting-custom-domains-and-github-pages#https-errors

**Comment by bartdesmet** [comment]
Closing the issue here as it's tracked by owners of ReactiveX.io over here: https://github.com/ReactiveX/reactivex.github.io/issues/389.
