### ISSUE TITLE
SelectMany(Func<TSource, Task<TResult>>) does not play nicely with Observable.Using

### ISSUE THREAD

**Issue by Lukazoid** [dotnet/reactive#172]
The overload of `SelectMany<TSource, TResult>` which takes `Func<TSource, Task<TResult>>` and `Func<TSource, CancellationToken, Task<TResult>>` propagates exceptions via the resulting observer immediately, forgetting about ongoing TAP (task-based asynchronous pattern) callbacks. 

Unfortunately this causes issues when the TAP callback makes use of `IDisposable` resources, as can be demonstrated by this example ([linqpad query](http://share.linqpad.net/u7ax8h.linq)):

```
Observable.Using<int, SemaphoreSlim>(() => new SemaphoreSlim(1,1), s =>
{
    int invocation = 0;
    return new[] { 1000, 2000, 3000 }.ToObservable()
        .SelectMany(async x =>
        {
            if(Interlocked.Increment(ref invocation) == 3)
               throw new Exception();

            await s.WaitAsync().ConfigureAwait(false);
            try
            {
                // This could be some other asynchronous method call
                await Task.Delay(x).ConfigureAwait(false);
            }
            finally
            {
                try
                {
                    s.Release();
                }
                catch (Exception ex)
                {
                    ex.Dump();
                    throw;
                }
            }

            return x;
        });
}).Dump();
```

The line `s.Release()` throws an `ObjectDisposedException` because the exception has caused the resource to be disposed.

Because of the nature of TAP the continuation could continue at any point, I believe this  demonstrates that it is also possible for `s.Release()` to be called concurrently with `s.Dispose()`, this is explicitly forbidden on many `IDisposable` implementations, meaning `Using` and these overloads of `SelectMany` cannot be used together.

For these reasons I believe the TAP based overloads of `SelectMany` should be changed to only propagate the first exception once all ongoing asynchronous invocations have been finished (completed, cancelled or faulted). 

An exception occurring should cancel the `CancellationToken` parameter passed to each of the TAP callbacks but this exception should not be passed to the `IObserver` until all callbacks have finished. It is optional but callbacks which complete successfully after an exception could still have their result passed to `IObserver<T>.OnNext(T)` before the exception. Having a value missing for the faulted callback is not an issue as these TAP overloads do not preserve order anyway.

**Comment by RxDave** [comment]
It's an interesting problem; however, have you considered that `Task` doesn't guarantee a result? If Rx holds back the exception until all continuations have terminated, then it's theoretically possible for an observer to never see the exception.

Here's a makeshift example of a continuation that never terminates:
```c#
while (true)
{
  try { await ThrowAsync(); }
  catch { }
}
```

Furthermore, the fact that all of your tasks depend on a resource means that if one fails you probably do want all of them to be terminated ASAP rather than letting them limp on in an unknown state. In your case, you want the resource to be alive, but that's just an arbitrary example, What if the exception was thrown by the resource itself, leaving it in an indeterminate state? You still want all of the existing continuations to execute without being cancelled?

Lastly, in the event that other tasks fail with different exceptions, how would the exception be propagated back to the observer? Would all of the exceptions have to be wrapped in an AggregateException?

In this particular example, I think the problem is simply that you're tying the lifetime of the resource to the lifetime of the observable, yet you're using it across multiple asynchronous invocations that aren't necessarily directly tied to the lifetime of the observable. Perhaps the best solution for you is to explicitly control termination of the `Using` operator yourself? Essentially, you'd be doing exactly what you're asking for, without requiring `SelectMany` to have a different behavior from every other operator, regarding Rx's fail-fast policy.

For example (untested):

```c#
Observable.Using<int, SemaphoreSlim>(() => new SemaphoreSlim(1,1), s =>
{
    int invocation = 0;
    return new[] { 1000, 2000, 3000 }.ToObservable()
        .SelectMany(async x =>
        {
          try {
            ...
            return Tuple.Create(x, (Exception)null);
          } catch (Exception ex) {
            return Tuple.Create(0, ex);
          }
        })
        .Scan(
           new { Value = (int?)null, Errors = new IEnumerable<Exception>() }, 
           (acc, cur) => new { 
              Value = cur.Item2 == null ? cur.Item1 : null, 
              Errors = cur.Item2 == null ? acc.Errors : acc.Errors.Concat(new[] { cur.Item2 }) })
        .Publish(p => 
           (from result in p
            where result.Value.HasValue
            select result.Value)
           .Merge(
            from result in p.TakeLast(1)
            select result.Errors.ToList() into errors
            where errors.Count > 0
            from _ in Observable.Throw(new AggregateException(errors))
            select default(int)));
});
```

**Comment by Lukazoid** [comment]
With your continuation which never terminates, it implies you would rather SelectMany notified the observer of the first exception and left the endless continuation running for the lifetime of your application? I would personally rather encounter a "block" here so I can either hook up this continuation to cancellation correctly or remove the infinite loop.

> What if the exception was thrown by the resource itself, leaving it in an indeterminate state? You still want all of the existing continuations to execute without being cancelled?

I never said I would want other continuations to execute, I would rather the other callbacks got cancelled rather than attempting to continue with a possibly corrupt resource:

> An exception occurring should cancel the CancellationToken parameter passed to each of the TAP callbacks

I would rather those tasks which completed propagated their result and then the first which encountered an exception propagated said exception, at least this way I am fully notified of which callbacks completed successfully. As it is, I have no way of knowing without a fair amount of work.

As it stands I just don't think `SelectMany` with the TAP overloads is very useful as it can leave tasks ongoing with no indication of whether they actually completed or not. This is less an issue of `Using` and more an issue of the implementation of `SelectMany`.

**Comment by Lukazoid** [comment]
It looks like other implementations have `mergeDelayError` which seems like what I would be after.

**Comment by akarnokd** [comment]
The issue is a bit old. If still relevant, there is a [merge implementation](https://github.com/akarnokd/reactive-extensions/blob/2407d03b5b18b6cf83372cecd66ebf5f6d6f6558/reactive-extensions/observable/MergeMany.cs) you could use through the library or take by source.
