### ISSUE TITLE
Items not processed, when busy processing previous items

### ISSUE THREAD

**Issue by Schand1** [dotnet/reactive#1846]
### Bug

> Which library version?

System.Reactive 5.0.0

> What are the platform(s), environment(s) and related component version(s)?

.Net 6

> What is the use case or problem?

I'm using Rx to process events in groups of maximal X items or after no new events were sent for Y ms. 
For this purpose I use the code suggested in this [stackoverflow](https://stackoverflow.com/a/9791385/20580963) answer. 

When I changed the code to wait until all events in the queue are processed, I noticed that some events get stuck in the queue.

> What is the expected outcome?

I would expect, that all events added to queue would be processed eventually, even when the queue is currently busy processing.

> What is the actual outcome?

When the queue is busy processing, events get "stuck" in the queue. Therefore the events which were sent while processing, will not be processed until a new entry is added to the queue after the previous processing finished.

> Do you have a code snippet or project that reproduces the problem?

To reproduce the behavior I wrote some sample code which adds numbers to the `subject` and then waits until the number is processed or the timeout is hit (`10sec`). 
If the number is processed another number is added. 
This second number is sent while the processing of the previous number is still busy, this leads to the described behavior.
This behavior can also be reproduced without any delay, it just won't happen regularly, because the timing has to be just right for it to happen.

```c#
private DispatcherScheduler _schedulerProviderDispatcher = new DispatcherScheduler(Application.Current.Dispatcher);
private Subject<int> _numberEvents = new Subject<int>();
private readonly ConcurrentDictionary<int, object> _numbersInProgress = new ConcurrentDictionary<int, object>();
private IDisposable _disposable;

public async Task SendNumbersAsync()
{
    _disposable = _numberEvents.Synchronize()
        .BufferUntilInactive(TimeSpan.FromMilliseconds(2000), _schedulerProviderDispatcher, 100)
        .Subscribe(numbers =>
        {
            if (numbers.Count == 0)
                return;

            var values = string.Empty;

            // Handle numbers in queue and remove them from the dictionary
            for (var i = 0; i < numbers.Count; ++i)
            {
                var number = numbers[i];
                if (_numbersInProgress.TryRemove(number, out _) == false)
                    Trace.WriteLine($"Failed to remove number '{number}'");

                values += $"{number}, ";
                Trace.WriteLine($"Handled Number: {number}, Count: {i + 1}/{numbers.Count}");
            }

            Trace.WriteLine($"Handled '{numbers.Count}' numbers. Values: '{values}'");

            // delay the execution by 1000ms to simulate a slow processing of the numbers
            // and create a timeframe where new numbers will be sent and received, but the subject is still busy with the previous processing 
            var task = Task.Delay(1000);
            Task.WaitAll(task);

            Trace.WriteLine($"Finished handling '{numbers.Count}' numbers. Values: '{values}'");
        });

    // push numbers to the subject
    var number = 0;
    while (_numbersInProgress.Count == 0)
    {
        ++number;
        Trace.WriteLine($"Sending number: {number}");
        _numberEvents.OnNext(number);
        Trace.WriteLine($"Finished sending number: {number}");

        // add the number to the progress dictionary
        if (_numbersInProgress.TryAdd(number, 0) == false)
            Trace.WriteLine($"Failed to add number '{number}'");

        var waitCount = 0;
        var timedOut = false;
        // wait for the numbers to be processed
        // if we waited 100 times (10sec) stop
        while (_numbersInProgress.Count != 0)
        {
            Trace.WriteLine($"Waiting ({waitCount})");
            await Task.Delay(100);
            ++waitCount;

            if (waitCount > 100)
            {
                timedOut = true;
                break;
            }
        }

        if (timedOut)
            Trace.WriteLine($"Timeout waiting: {number}");
        else
            Trace.WriteLine($"Finished waiting: {number}");
    }

    // if we still have unprocessed numbers
    // send another number to the subject to trigger processing of both numbers
    if (_numbersInProgress.Count != 0)
    {
        // Failed
        Trace.WriteLine($"Failed waiting: {number}");

        Trace.WriteLine($"Sending number: {9999}");
        _numberEvents.OnNext(9999);
        Trace.WriteLine($"Finished sending number: {9999}");
    }
}
```
And the extension method, used to group the numbers:

```c#
public static IObservable<IList<T>> BufferUntilInactive<T>(this IObservable<T> stream, TimeSpan delay, IScheduler scheduler = null, Int32? maxCount = null)
{
     var s = scheduler ?? Scheduler.Default;

     var publish = stream.Publish(p =>
     {
          var closes = p.Throttle(delay, s);

          if (maxCount != null)
          {
              var overflows = p.Where((x, index) => index + 1 >= maxCount);
              closes = closes.Amb(overflows);
          }

          return p.Window(() => closes).SelectMany(window => window.ToList());
     });

     return publish;
}
```

### Output
When executing this method, the trace outputs the following lines:
![Rx_Console_Output](https://user-images.githubusercontent.com/47356358/206175605-30e4211f-f6b5-4b8f-87f1-3118a0ce5d9e.jpg)

number 2 is sent before the processing of the previous sent number 1 is finished

![Rx_Console_Output2](https://user-images.githubusercontent.com/47356358/206175808-1f1b9b90-5c01-413d-9016-76b5c7f84076.jpg)

the loop runs in the timeout condition after 100 wait cycles and then sends a new number, which triggeres the processing of both numbers in the queue

**Comment by Schand1** [comment]
Thanks for the reply,

I tried your suggested solution and with a little change in the extension method the error was fixed.
I needed to ajust the maxCount, without the change the maxCount would never be reseted and after it was hit once, every new event would be over the maxCount.

```C#
public static IObservable<IList<T>> BufferUntilInactive<T>(this IObservable<T> stream, TimeSpan delay, IScheduler scheduler = null, Int32? maxCount = null)
{
     var s = scheduler ?? Scheduler.Default;

     var publish = stream.Publish(p =>
     {
          var closes = p.Throttle(delay, s);

          if (maxCount != null)
          {
              Int32 i = 0;
              var overflows = p.Where(x =>
              {
                  ++i;

                  if (i >= maxCount)
                  {
                      i = 0;
                      return true;
                  }

                  return false;
              });

              closes = closes.Amb(overflows);
          }

          return p.Window(closes).SelectMany(window => window.ToList());
     });

     return publish;
}
```

Thanks again for the help and the insight where my wrong understanding of the code happened.

**Comment by Schand1** [comment]
Sorry to bother you again, 
but after some more testing with the production code, the same error occured again, although the test code showed no errors.

It seems, that even with the suggested change, there is still a timeframe in which events won't be processed.
The error behavior is exactly the same as before, some events get stuck in the queue and because I am waiting for them to be processed, I am deadlocked.

I used a workaround for the past 4 Months which resolved the problem, but it only seems to work with the previous implementation of the `p.Window(() => closes)`. 
By adding a Delay with any `TimeSpan` the problem stopped occuring.

Can you give me some insight into the impact of the `Delay()` to this behavior and why it prevents the error to occur?

```c#
public static IObservable<IList<T>> BufferUntilInactive<T>(this IObservable<T> stream, TimeSpan delay, IScheduler scheduler = null, Int32? maxCount = null)
{
     var s = scheduler ?? Scheduler.Default;

     var publish = stream.Publish(p =>
     {
          var closes = p.Throttle(delay, s);

          if (maxCount != null)
          {
              var overflows = p.Where((x, index) => index + 1 >= maxCount);
              closes = closes.Amb(overflows);
          }

          return p.Window(() => closes).SelectMany(window => window.ToList()).Delay(TimeSpan.Zero, s);
     });

     return publish;
}
```

Do you have any other idea why I am still experiencing this behavior, even after changing the code?

**Comment by idg10** [comment]
> Do you have any other idea why I am still experiencing this behavior, even after changing the code?

Well, the answer last time wasn't a bug in Rx, it was a bug in the code you showed me. Now you're telling me that although the test code you've shown me no longer fails (you said "the test code showed no errors,") you still see problems in your production code.

So one possibility is that this still isn't a bug in Rx, and that this time it's a bug in some of the code you've not shown me.

Although it's not out of the question that there could be a bug in Rx, there's nothing at all for me to go on here. If you can't show me code that exhibits the problem, it's likely to be impossible for me to work out why it's happening, because the cause of the problem could be in some code that's only running in your production system.

With the information you've given me, about the only helpful thing I can possibly try to do here is to answer this:

>Can you give me some insight into the impact of the Delay() to this behavior and why it prevents the error to occur?

Using this operator will cause everything that emerges from the `SelectMany` to be deferred through the scheduler before coming out of the `IObservable` returned by `BufferUntilInactive`. This can change the exact timings with which things occur, and if you've got race condition bugs, doing something that changes the timings even slightly might mask (or reveal) those bugs. Since the problem you describe has something to do with whether events fall into a narrow timespan, it's not wholly surprising that a change that makes no logical difference to the behaviour but which will likely change the scheduling will disturb the behaviour.

You've re-opened this issue, but you've not provided any further information that might point to a problem in Rx. (And the information you already provided only exhibited problems fully explained by a bug in the test code.) If you can supply example code that exhibits a problem, I can take a look at it, but if not, I'll have to reclose the issue because there's nothing for me to base any further investigation on.

**Comment by NickStrupat** [comment]
FYI still there in Rx 6.0 on .NET 8

**Comment by idg10** [comment]
This appears not to be a bug in `Window`, but a feature of combining `Do` and `SelectMany` in this way. Rx has in fact done precisely what you've asked. I know you didn't _intend_ to ask it to ignore that `X` event, but the way you've written your code means that Rx is positively obliged not to deliver that `X` event where you're expecting it to go. (It's not actually dropping it though, as I'll demonstrate. It's that you've created a situation where the event is delivered before your code is has asked to receive it.)

>the value 'X' is injected during this event, and it escapes observation by the newly created window.

That statement is not quite accurate. The newly created window receives the event and duly distributes it to all of its subscribers. The problem is that nothing has yet subscribed to that window when you call `synchronized.OnNext('X');`. And that's happened because that's what your code has asked for.

We can make this a bit more obvious by adding some logging to the `SelectMany` callback:

```cs
.SelectMany(window =>
{
    Print("SelectMany received new window");
    return window.ToList();
})
```

That produces this output:

```
07:28:53.092 [1] > Window #1 emitted
07:28:53.113 [1] > SelectMany received new window
07:28:53.174 [7] > Produced: A
07:28:53.284 [7] > Consumed: [A]
07:28:53.286 [7] > Window #2 emitted
07:28:53.287 [7] > Produced: X
07:28:53.287 [7] > After OnNext('X') injection
07:28:53.287 [7] > SelectMany received new window
07:28:53.684 [4] > Producer Completed
07:28:53.685 [4] > Consumed: []
07:28:53.686 [4] > Consumer Completed
07:28:53.688 [4] > Results: [A], []
```

This makes it clear that the `SelectMany` callback doesn't run until after your `Do` callback has injected the `X` value. And since it's that callback that subscribes to window, your code never receives the item.

So it's not that `Window` is losing the item. It's that you haven't yet subscribed to the window at the moment that you produce that item.

And you should expect this. You've inserted that `Do` before the `SelectMany`, so you are asking Rx to invoke your `Do` callback before it passes each window on to `SelectMany`. It has done exactly what you asked it to do: it has given you access to the new window before `SelectMany` got to see it. So you should not be surprise that Rx gives you the window before it has any subscribers. You should thank it for doing precisely what you asked. 😉

We can further demonstrate that `Window` really isn't losing anything by adding yet another `Do`:

```cs
IList<char>[] results = await subject
    .Do((char x) => Print($"Produced: {x}"), () => Print($"Producer Completed"))
    .Window(subject.Throttle(TimeSpan.FromMilliseconds(100)))
    .Do(w => w.ToList().Subscribe(l => Print($"Pre-Do window subscription received [{string.Join(", ", l)}]")))
    .Do(_ =>
    {
        i++;
        Print($"Window #{i} emitted");
        if (i != 2) return;
        // Inject the value X in the 2nd window only.
        synchronized.OnNext('X');
        Print($"After OnNext('X') injection");
    })
    .SelectMany(window =>
    {
        Print("SelectMany received new window");
        return window.ToList();
    })
    .Do((IList<char> w) => Print($"Consumed: [{String.Join(", ", w)}]"),
        () => Print($"Consumer Completed"))
    .ToArray();
```

The extra `Do` appears before before your injecting `Do`. Rx does things in the order you tell it to (which is why your example doesn't behave how you had hoped, by the way), so this gets to run before your original `Do` callback. That means this added code will have a chance to subscribe to each new window before your injection occurs. Here's the output:

```
07:34:34.316 [1] > Window #1 emitted
07:34:34.336 [1] > SelectMany received new window
07:34:34.392 [7] > Produced: A
07:34:34.502 [7] > Pre-Do window subscription received [A]
07:34:34.504 [7] > Consumed: [A]
07:34:34.505 [7] > Window #2 emitted
07:34:34.505 [7] > Produced: X
07:34:34.505 [7] > After OnNext('X') injection
07:34:34.505 [7] > SelectMany received new window
07:34:34.906 [8] > Producer Completed
07:34:34.906 [8] > Pre-Do window subscription received [X]
07:34:34.906 [8] > Consumed: []
07:34:34.907 [8] > Consumer Completed
07:34:34.909 [8] > Results: [A], []
```

Note in particular, this line:

```
07:34:34.906 [8] > Pre-Do window subscription received [X]
```

There's your X. This proves conclusively that the item did not in fact escape observation by Rx. The window captured the event exactly as it is supposed to. It reported it to all the window's active subscribers exactly as it is supposed to. (So the 'bug' here does not exist. The item is not lost.)

It is true that Rx did not report this item to the subscription _that hadn't actually been set up yet_ at the time that the event occurred. That is not a bug. `Window` is not designed to hold onto items until such time as you're ready to subscribe.

In short, this code has gone out of its way to be able to send an item into the window before that `SelectMany` had the opportunity to subscribe to the window. Rx has done precisely what the code asked it to do. The effect is that your code doesn't see the `X` in the output of the `SelectMany`, but that's because you told Rx to do things in a way that ensured that this would be the case.

## Do or do not?

This is a good example of why I try never to use `Do`. It can seem very convenient but in my experience it is almost always trouble.

The nature of the trouble is that it's typically very hard to reason about what will actually happen. For example, by adding a little bit of extra log output to your code, I hope it is now clear that the reason the `X` appears to go missing is because `Do` runs before `SelectMany` gets to see the window from which that `X` can emerge. (And this happens because that's what you told Rx to do.) However, I did not find this obvious. I had to think about this for quite a while to understand that this is what was happening.

I suspect I would not have noticed the problem in a code review. (Although if I had been reviewing this code I would have strongly recommended finding a way of not using `Do` simply because I know from experience that `Do` is usually a bad idea.) And that's the problem with `Do`. It makes logic errors in the code very hard to spot.

Why is that? I think it's a combination of two factors. One is that `Do` is essentially an imperative style of code, whereas Rx (and LINQ in general) was designed to be used in a functional style. `Do` provides a kind of escape hatch, and sometimes you can't avoid it, but it's best to think of it as a last resort.

And the second factor follows from the first: by moving into an imperative idiom, you suddenly need think more about how Rx actually does things. If you avoid `Do`, you can think about Rx subscriptions at a fairly high level of abstraction. You can think a stream of `char`s being split into windows that are collected by `SelectMany`. You generally don't need to ask yourself exactly how and when Rx makes the necessary method calls. You don't need to think about the fact that you've passed a callback method in as the argument to `SelectMany` that will need to run at some specific moment—you can just think about the abstract operation of `Window` and `SelectMany`.

In fact, I'd go as far as to say that the ability to think at this higher level of abstraction is Rx's biggest selling point.

But `Do` defeats that.

By introducing `Do` the behaviour of the code is now much more sensitive to how Rx actually does things in practice. Actually, in particular it's the fact that one of the `Do` callbacks pushes new items into the upstream source—this creates a feedback loop that exists entirely outside of the core LINQ abstractions that Rx is modelled on.

That makes this code relatively hard to understand. By using `Do` and by pushing items into the upstream source in the `Do` callback, you've now made the fact that `SelectMany` has to invoke the callback you supplied a relevant factor in the behaviour. (And it could get a whole lot harder to understand once schedulers get involved. I would say that you really never want to be in a position where you have to understand exactly how particular schedulers do things, but if you use `Do`, you may well be putting yourself in exactly that position.)

So in conclusion:
* There is no evidence of a bug in Rx here—it did what you told it
* Your code causes items to go into a window before that window has any subscribers
* Avoid `Do` if at all possible

**Comment by theodorzoulias** [comment]
Thanks @idg10 for the superb explanation of my minimal repro. I agree that there is no bug in Rx here, and the behavior that caught me by surprise was the correct behavior to be expected from Rx.

Have you also studied the code posted by @Schand1 in the opening comment of this issue? Their issue might not be identical with the issue in my repro. I am worried that the custom Rx operator [`BufferUntilInactive`](https://stackoverflow.com/questions/7597773/does-reactive-extensions-support-rolling-buffers/9791385#9791385) that has been posted by Colonel Panic on StackOverflow might be buggy. It's likely that many people have used this operator in their projects, because it performs a function that is both useful and common.

**Comment by theodorzoulias** [comment]
@HowardvanRooijen yes, the `Quiescent` is essentially the same operator with the `BufferUntilInactive`, apart from the _maximum count_ functionality. Colonel Panic has posted a simpler `BufferUntilInactive` version without maximum count policy in [another StackOverflow question](https://stackoverflow.com/questions/8849810/reactive-throttle-returning-all-items-added-within-the-timespan/9791918#9791918 "Reactive Throttle returning all items added within the TimeSpan"). Both of his answers were posted the same day (Mar 20, 2012). He has used the `Window` Rx operator as the basis of his implementations, contrary to the `Quiescent` that is based on the `Buffer` Rx operator. Using the `Window` is more risky, because if you don't subscribe to these windows immediately you might lose messages (as it happened to me in my repro). With the `Buffer` there is nothing to subscribe to, so this risk factor does not exist.

**Comment by idg10** [comment]
@theodorzoulias 

>Have you also studied the code posted by @Schand1 in the opening comment of this issue? 

I explained what was wrong with that in my first reply in this thread.

If you look at https://stackoverflow.com/a/75926551/497397 you can see that someone added an answer to that stack overflow page based on my reply.
