### ISSUE TITLE
Add short description of all projects to start of readme

### ISSUE THREAD

**Issue by idg10** [dotnet/reactive#1881]
The discussion at https://github.com/dotnet/reactive/discussions/1868#discussioncomment-5051485 has revealed that the repo-level readme file does not do a great job of guiding people who arrived at the repo (perhaps via the link on NuGet) without knowing very much about Rx. It's not obvious what's in here, and why there are several apparently different features in different libraries all in one repository.

We need a succinct description of the things that are in this repository. It contains:

* Rx.NET (aka `System.Reactive`)
* LINQ for `IAsyncEnumerable` (aka `System.Linq.Async`)
* Ix.NET (aka `System.Interactive`)

These are somewhat different things (although they're conceptually united under "LINQ to everything" and more specifically "LINQ over sequences of things" which is why all three are in the same repo). So we should add a brief "What's in here, what's it for, and where do I look next to find out more?" section, answering those questions for each of the three things above.

**Comment by idg10** [comment]
While we're updating readme files, we should look at https://devblogs.microsoft.com/nuget/write-a-high-quality-readme-for-nuget-packages/

**Comment by idg10** [comment]
We also get a load of warnings when we publish to NuGet about the use of the deprectated `<iconUrl>`. We should update to the current practice.

**Comment by idg10** [comment]
Consider also adding a badge for the latest preview build https://img.shields.io/nuget/vpre/System.Reactive.svg

**Comment by idg10** [comment]
While we're at it, add a change log for the v6.0 release

**Comment by WhitWaldo** [comment]
I fully agree the home README could use a rewrite to make it easier for new developers to understand the purpose of the various things in the repo and better understand how they might be used for one reason or another. Rxjs does a great job of this on their [Getting Started](https://rxjs.dev/guide/overview) page outside of the repo.

I'd follow RxJs's lead and build out a Getting Started/API Docs site somewhere on which you can replicate something like their explanations of the different Observable components, show some marble diagrams illustrating how the different operators work and generally get into more detail about each of the libraries in the project.

Here in the repo, I think having a richer description for Rx, Ix and System.Linq.Async would do wonders, especially if you can point to the Getting Started page to identify content for new users about what exactly observables even are. While there's a paragraph and table under [A Brief Intro](https://github.com/dotnet/reactive#a-brief-intro) that sort of gets into this, I think it does a poor job of illustrating the different problems each of the projects in this repo intend to solve (I mean, there are three projects in the repo and this table has two rows, so that's already confusing in itself).

**Comment by idg10** [comment]
We are currently working on bringing a site with a more comprehensive guide to Rx.NET up to date. (There's an existing site, and we're working to update it, with permission from the original author.) Once that's ready I'll add links as you suggest. Meanwhile, we will have richer descriptions for each element as you describe, which will be an improvement for the time being, until we're ready to release the updated guide site.
