### ISSUE TITLE
TestScheduler WithAsync swallows all exceptions making all tests pass

### ISSUE THREAD

**Issue by MarshMello0** [dotnet/reactive#2096]
# Bug

In Unit testing, when doing TestScheduler().WithAsync any expection doesn't fail the test.

[I did find this stackoverflow question](https://stackoverflow.com/questions/60414905/how-to-unit-test-exceptions-from-reactivecommand-reactiveui), which is super close to the same senario but not fully

## Which library version?

6.0.0

## What are the platform(s), environment(s) and related component version(s)?

.NET 6 

## What is the use case or problem?

All tests passing, even though they are failing by throwing exceptions.

## What is the expected outcome?

Tests that throw exceptions, fail

## What is the actual outcome?

Tests that throw exceptions, pass

## Do you have a code snippet or project that reproduces the problem?

```cs
[Test]
public void Test() => new TestScheduler().WithAsync(async scheduler =>
{
    await Task.Delay(1);
    throw new Exception("This should fail the test");
});
```

**Comment by idg10** [comment]
What's this `WithAsync` method?

I've searched the whole Rx.NET source repo, and we do not define any such method.

Right now if you search: https://github.com/search?q=repo%3Adotnet%2Freactive%20WithAsync&type=code the only result for `WithAsync` is this issue that you opened.

I'm going to hazard a guess that you're using ReactiveUI (which uses Rx, but is a separate thing from Rx).

If that's correct, there's an obvious problem with your test: ReactiveUI's `WithAsync` method returns a `Task`, but your test returns `void`. That means that you've given the unit test framework no way of knowing when your test actually finished.

Since `WithAsync` more or less immediately returns a `Task`, which you then fail to return from your test, so the test runner thinks your test is done.

If we simply change the return type of your test from `void` to `Task`:

```cs
[Test]
public Task Test() => new TestScheduler().WithAsync(async scheduler =>
{
    await Task.Delay(1);
    throw new Exception("This should fail the test");
});
```

then the test fails in exactly the way you want.

This works because by returning the `Task`, you've made it possible for the test runner to wait for your test to finish, and to discover whether it threw any exceptions. By returning `void` you were making it impossible for the test runner to find out what the outcome of your code was.

**Comment by MarshMello0** [comment]
doh, aplogies. Looking back on this and the code, yes it is from the namespace `ReactiveUI.Testing`. 

Thank you for explaining the solution as well in great detail! That makes sense now
