### ISSUE TITLE
Possible Bug: Retry does not work on an observable created using the Start operator

### ISSUE THREAD

**Issue by Sathyaish** [dotnet/reactive#238]
Running the following code snippet only tries the `DownloadString` operation once and gives up on the first failure where it should have retried 3 times before reporting failure.

``` csharp
using System;
using System.Net;
using System.Reactive.Linq;
using System.Threading;

namespace RetryingOperation
{
    class Program
    {
        static void Main(string[] args)
        {
            RetryDownloadStringAsynchronously();

            Console.WriteLine("Press any key to exit the program");
            Console.ReadKey();
        }
        static void RetryDownloadStringAsynchronously()
        {
            Console.WriteLine($"Main thread: {Thread.CurrentThread.ManagedThreadId}");

            string url = "http://www.nonexistent.com";

            var observable = Observable.Start(() => DownloadString(url));

            observable.Retry(3).Subscribe(Console.WriteLine, Error, Completed);
        }

        static void Completed()
        {
            Console.WriteLine("The operation completed successfully.");
        }

        static void Error(Exception ex)
        {
            Console.WriteLine($"Error handler reports: There was an error: {ex.Message}");
        }

        static string DownloadString(string url)
        {
            try
            {
                Console.WriteLine($"DownloadString running on thread: {Thread.CurrentThread.ManagedThreadId}");

                return new WebClient().DownloadString(url);
            }
            catch
            {
                Console.WriteLine("Inside DownloadString: An exception occurred.");
                throw;
            }
        }
    }
}
```

Please note, however, that it works just fine without using the `Start` operator, as shown below.

``` csharp
using System;
using System.Net;
using System.Reactive.Linq;
using System.Threading;

namespace RetryingOperation
{
    class Program
    {
        private static bool flag = false;

        static void Main(string[] args)
        {
            RetryDownloadString();

            RetryDownStringEx();

            Console.WriteLine("Press any key to exit the program");
            Console.ReadKey();
        }

        static void RetryDownloadString()
        {
            try
            {
                Console.WriteLine($"Main thread: {Thread.CurrentThread.ManagedThreadId}");

                string url = "http://www.nonexistent.com";

                var observable = Observable.Return<Func<string, string>>(DownloadString)
                    .Select(func => func(url));

                observable.Retry(3).Subscribe(Console.WriteLine, Error, Completed);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Catch reports: {ex.Message}");
            }
        }

        static void RetryDownStringEx()
        {
            try
            {

                string url = "http://www.google.com";

                var observable = Observable.Return<Func<string, string>>(DownloadStringEx)
                    .Select(func => func(url));

                observable.Retry(3).Subscribe(Console.WriteLine, Error, Completed);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Catch reports: {ex.Message}");
            }
        }

        static void Completed()
        {
            Console.WriteLine("The operation completed successfully.");
        }

        static void Error(Exception ex)
        {
            Console.WriteLine($"Error handler reports: There was an error: {ex.Message}");
        }

        static string DownloadString(string url)
        {
            try
            {
                Console.WriteLine($"DownloadString running on thread: {Thread.CurrentThread.ManagedThreadId}");

                return new WebClient().DownloadString(url);
            }
            catch
            {
                Console.WriteLine("Inside DownloadString: An exception occurred.");
                throw;
            }
        }

        static string DownloadStringEx(string url)
        {
            try
            {
                Console.WriteLine($"DownloadStringEx running on thread: {Thread.CurrentThread.ManagedThreadId}");

                if (!flag) url = "http://invalidUrl";

                return new WebClient().DownloadString(url).Length.ToString();
            }
            catch
            {
                flag = !flag;
                Console.WriteLine("Inside DownloadStringEx catch: Ooops!");
                throw;
            }
        }
    }
}
```

Also note that it works just fine when not using the `Start` operator even if I were to schedule the work on the default pool scheduler, as the code snippet below shows:

``` csharp
static void RetryDownloadString()
{
    try
    {
        Console.WriteLine($"Main thread: {Thread.CurrentThread.ManagedThreadId}");

        string url = "http://www.nonexistent.com";

        var observable = Observable.Return<Func<string, string>>(DownloadString, Scheduler.Default)
            .Select(func => func(url));

        observable.Retry(3).Subscribe(Console.WriteLine, Error, Completed);
    }
    catch (Exception ex)
    {
        Console.WriteLine($"Catch reports: {ex.Message}");
    }
}
```

**Comment by danielcweber** [comment]
Can you rework this into a simple unit test and create a pull request?

**Comment by Sathyaish** [comment]
@danielcweber Sure, will do at my earliest convenience. Thank you.

**Comment by bartdesmet** [comment]
Not a bug. Start returns a hot observable, so operators like Retry won't have an effect on it. It's pretty much the same as turning the synchronous function into a Task, except we use an observable to represent the outcome.

**Comment by Sathyaish** [comment]
Thanks, @bartdesmet.

Why shouldn't it be possible to retry observing a hot sequence if an attempt to observe fails?

Is that because hot sequences are thought of as being "out of the control of the observer" and as having potential side-effects? So retrying them simply because an observation (and not the event itself) failed could mean replaying unintended side-effects?

In contrast, a cold observable is, by design, meant to be replayed for each subscriber, so retrying them is quite safe?

I am now suddenly left wondering, when we retry, what are we actually retrying? Are we retrying:

1. Running the observable again? or
2. Simply retrying an attempt to observe an observable?

In both cases, though, you're right, retrying a hot observable makes little sense.

**Comment by RxDave** [comment]
@Sathyaish See if this helps: 
http://davesexton.com/blog/post/Hot-and-Cold-Observables.aspx

**Comment by bartdesmet** [comment]
@Sathyaish, your intuitions are more or less correct, but allow me to add some detail nonetheless.

Let's start by analyzing the simplest case of `io.Subscribe(iv)` and question the possible outcomes of this. Clearly, we could observe any sequence of notifications conform the Rx grammar. This includes absolute silence, as if `io` is equivalent to `Never<T>()`.

When we observe such behavior (or rather don't observe anything, ignoring the fact we'd have to wait *forever*), what can we conclude about the nature of the source sequence? Not much really... It could be *cold* or *hot*.

Let's pretend the source is *hot* for a moment. Now the question becomes whether this source has *ever* produced a non-empty sequence and we tuned in too late (i.e. after `OnError` or `OnCompleted`), or it's still running and genuinely producing silence.

So what about the case of arriving too late to the party and having missed all notifications, including terminal ones? If were to apply `Retry` to such a sequence, what'd the outcome be? The operator would observe the `OnError` message indicating the end of times for the hot sequence and subscribe to the sequence again (*after* its final notification), only to be faced with absolute silence forever. We've just covered up an error and pretty much turned it into `.Catch(Never<T>())`, which is the equivalent to 'try { ... } catch { Thread.Sleep(Infinite); }' in the synchronous world. (No, it's not `.Catch(Empty<T>())` which would be `try { ... } catch { }`).

Wow, that's concerning, isn't it? Luckily many hot sequences, including `ISubject<T>` implementations in Rx, have some memory to deal with this and let late subscribers know of the final outcome that has taken place. They're in effect behaving like `Throw<T>(ex)` or `Empty<T>()` after reaching a final `OnError` or `OnCompleted` state. Note that other hot sequences, e.g. observable wrappers around a network resource producing packets, may not have this luxury of keeping state forever on the sender side. However, the non-existence of the source is an equally valid piece of state, e.g. the `Subscribe` method throwing due to e.g. a `404` error, or an `ObjectDisposedException`.

Okay, so what if a hot resource does indeed have some memory to cover up the absence of notifications coming out after reaching a terminal state? Are we no longer "asynchronously deadlocked" when applying `Retry`? In fact, it's worse, provided we don't have an upper bound to the number of retries! Now when we subscribe to the source from within `Retry`, we'll see an `OnError` coming out and process it by retrying again, leading to another observation of the same `OnError`, etc. We've now turned it into something like `for (;;) { try { ... break; } catch { continue; }` where you imagine the `...` part to throw each and every time because it *remembered* to behave like that forever.

What this all boils down to is that one should know darn well about the behavior of the sequence one applies `Retry` to. This is no different from the synchronous world where a retry is effectively a loop construct around an exception handling construct. If you don't know whether the code being *tried* will insist on failing over and over again, your only hope is to have an upper bound to the number of retries.

So, where's `Retry` useful? Cold sequences for sure, because you can start their underlying computation all over again. If the sequence behaves as a pure function terminating with an `OnError`, you're back to the infinite loop case of course.

Another case where `Retry` is useful is when you apply *operators* to hot (or cold) sequences, which are really just functions returning *cold* sequences (in general, ignoring things like `Publish` and `RefCount` which create some intermediate *connectable* thing to control the timing of cold/hot transitions, a thermostat really). For such cases, you can retry whatever logic these operators encapsulate, e.g. `xs.Where(x => 1 / x).Retry()` encountering a value of `x` that's zero, causing a downstream `OnError` notification containing `DivideByZeroException`. What are the guarantees though? It depends an awful lot on the behavior of the source *again*!

What happens here really? The source sent an `OnNext` which synchronously was translated to an `OnError` due to an error in the `Where` operator, which on its turn is observed by `Retry`. At this point, the `Retry` operator *synchronously* subscribes to its source, which ultimately bubbles up to `xs`, so we're seeing *reentrancy* of `Subscribe` during an outgoing `OnNext` call! At this point, it's pretty much implementation dependent what will happen...

Does the new incoming observer simply get added to the list of current observers? Was that list snapshotted prior to sending out notifications? If it wasn't, we'll receive the same `OnNext` message again, causing the same error, resulting in a `Retry`, and we'll stall the hot source from making progress ever again; it will see an ever-appending list of observers growing while processing a message, ultimately leading to `OutOfMemoryException`. This is exactly the case where "the collection was modified during enumeration" can expedite death, but it's not pretty in any case: we either never get to the next message, or fail to deliver it to all observers following the reentrant one.

Luckily, in Rx, we use a snapshot of the observers when sending out a notification (see `Subject<T>` for an example on its use of an immutable observers "collection" and some low-locking techniques to avoid big locks), so you're protected from this type of reentrant behavior causing a stall or crash. Provided your whole query is synchronous (i.e. no `ObserveOn` operators and whatnot), you'll end up skipping the current `OnNext` message that turned into an `OnError` and tune in to the next one.

However, this doesn't mean that `Retry` is easy to reason about even then. For example, consider `xs.Where(f).Take(5).Retry()` versus `xs.Where(f).Retry().Take(5)`. In the first case, you'll get zero *or more* elements (think about all the cases, think about what you're retrying here, and think about all the hidden state). In the second case, you'll get *at most* 5 elements.

Also, the hot sequence may exhibit asynchronous subscription behavior relative to the outgoing notifications, so the behavior of a `Subscribe` coming in during an outgoing `OnNext` may be ill-defined, thus leaving gaps between your failure to observe an event and the events received through the newly created subscription by `Retry`. Even worse, if the source has replay behavior (e.g. `BehaviorSubject` or `ReplaySubject`) the new subscription will go *back* in time and eventually see the same event that caused the error in the first place (oh, and are the operators or functions passed to them pure or not?).

All in all, if you don't know what you're retrying (which can be a long chain of composed operators hidden behind an `IObservable<T>` of which you don't know the whole story), don't try to retry! The same advice holds for pull-based sequences (`IEnumerable<T>` is equally lazy, can hide an iterator, a replayable collection, etc.), and even more generally for any kind of code, be it synchronous or asynchronous. Effects may be hidden under the abstractions in many possible ways, so a `while` loop around ` try` always has a bitter taste to it. `Retry` is just that, but you won't make a powerful framework by taking away *potentially* dangerous utilities (just like you can't ban nail polish remover because someone can mix it with other ingredients to make a bomb).

**Comment by Sathyaish** [comment]
Wow! :-)

Thank you *so* much, @bartdesmet.

To parse your reply, I implemented bits and pieces of it. I am pasting the code snippets here so they may serve as a reminder to me and to any other like myself who is trying to learn Rx.

> Let's start by analyzing the simplest case of `io.Subscribe(iv)` and question the possible outcomes of this. Clearly, we could observe any sequence of notifications conform the Rx grammar. This includes absolute silence, as if `io` is equivalent to `Never<T>()`.

> When we observe such behavior (or rather don't observe anything, ignoring the fact we'd have to wait forever), what can we conclude about the nature of the source sequence? Not much really... It could be cold or hot.

> Let's pretend the source is hot for a moment. Now the question becomes whether this source has ever produced a non-empty sequence and we tuned in too late (i.e. after `OnError` or `OnCompleted`), or it's still running and genuinely producing silence.

> So what about the case of arriving too late to the party and having missed all notifications, including terminal ones? If were to apply `Retry` to such a sequence, what'd the outcome be? The operator would observe the `OnError` message indicating the end of times for the hot sequence and subscribe to the sequence again (after its final notification), only to be faced with absolute silence forever. We've just covered up an error and pretty much turned it into `.Catch(Never<T>())`, which is the equivalent to `'try { ... } catch { Thread.Sleep(Infinite); }'` in the synchronous world. (No, it's not `.Catch(Empty<T>())` which would be `try { ... } catch { }`).

> Wow, that's concerning, isn't it? Luckily many hot sequences, including `ISubject<T>` implementations in Rx, have some memory to deal with this and let late subscribers know of the final outcome that has taken place. They're in effect behaving like `Throw<T>(ex)` or `Empty<T>()` after reaching a final `OnError` or `OnCompleted` state. Note that other hot sequences, e.g. observable wrappers around a network resource producing packets, may not have this luxury of keeping state forever on the sender side. However, the non-existence of the source is an equally valid piece of state, e.g. the `Subscribe` method throwing due to e.g. a 404 error, or an `ObjectDisposedException`.

> Okay, so what if a hot resource does indeed have some memory to cover up the absence of notifications coming out after reaching a terminal state? Are we no longer "asynchronously deadlocked" when applying `Retry`? In fact, it's worse, provided we don't have an upper bound to the number of retries! Now when we subscribe to the source from within `Retry`, we'll see an `OnError` coming out and process it by retrying again, leading to another observation of the same `OnError`, etc. We've now turned it into something like for `(;;) { try { ... break; } catch { continue; }` where you imagine the `...` part to throw each and every time because it remembered to behave like that forever.

> What this all boils down to is that one should know darn well about the behavior of the sequence one applies `Retry` to. This is no different from the synchronous world where a retry is effectively a loop construct around an exception handling construct. If you don't know whether the code being tried will insist on failing over and over again, your only hope is to have an upper bound to the number of retries.

> So, where's `Retry` useful? Cold sequences for sure, because you can start their underlying computation all over again. If the sequence behaves as a pure function terminating with an `OnError`, you're back to the infinite loop case of course.

> Another case where `Retry` is useful is when you apply operators to hot (or cold) sequences, which are really just functions returning cold sequences (in general, ignoring things like `Publish` and `RefCount` which create some intermediate connectable thing to control the timing of cold/hot transitions, a thermostat really). For such cases, you can retry whatever logic these operators encapsulate, e.g. `xs.Where(x => 1 / x).Retry()` encountering a value of x that's zero, causing a downstream `OnError` notification containing `DivideByZeroException`. What are the guarantees though? It depends an awful lot on the behavior of the source again!


Thanks much much, @RxDave. I'll be reading the article you linked to soon and following-up on this thread if I have more related questions.

**Comment by glen-nicol** [comment]
I think I am having trouble that is similar and am not sure how to work around it.

```csharp
_displayOnPage = Observable.Defer(() => CreateSequenceWithSideEffectsThatChangeUI())
    .Publish()
    .RefCount();
...
public IObservable<Unit> Display()
{
    return _displayOnPage
}

.. else where

Display().Subscribe()
....

await Display();

```

This runs just fine the first time. But then on subsequenct subscribes the subscription immediately receives the OnComplete before the defer action is even executed. What I would like is to share the published stream until everyone unsubscribes(so the side effects aren't duplicated) and then if someone subscribes to it again it should reevaluate the original sequence.

Is that supposed to happen? If not how can I accomplish that?

I've found similar issues for [RXJS](https://github.com/ReactiveX/rxjs/issues/678) and [RXPy](https://github.com/ReactiveX/RxPY/issues/202) which is even linked.

**Comment by akarnokd** [comment]
Maybe the termination of the main source is racing with the refCount operator so that the observer gets in there only to receive the terminal event.

**Comment by glen-nicol** [comment]
I think it is because [publish just uses a subject](https://github.com/dotnet/reactive/blob/3964f9f8c0afb169b744c35d50247d58b054f8db/Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Binding.cs#L31) without any extra reuse logic. And Subjects aren't valid once they issue an onerror or oncompleted. Unless I misunderstand where publish is actually implemented.
