### ISSUE TITLE
Add an overload for ToAsyncEnumerable that takes a custom TaskScheduler

### ISSUE THREAD

**Issue by yariker** [dotnet/reactive#297]
Current implementation of `AsyncEnumerable.ToAsyncEnumerable<TSource>(this IEnumerable<TSource> source)` does not allow you to pass a custom `TaskScheduler`, thus, it provides no control on how the tasks are scheduled.

It would be nice to have an overload that takes a `TaskScheduler` (or maybe even a `TaskFactory<bool>`) as a parameter.

**Comment by shiftkey** [comment]
@krs500 can you give an example of how this is hard to control/test? For the most part we're using `Task.FromResult` (at least in 3.1) so I'd love to understand more about the problems you're facing and see what the net effect of this overload will be...

**Comment by krs500** [comment]
I just realized that in v3.1.0, the `ToAsyncEnumerable` behaves in a very different way than in v3.0.0. And I am stuck to v3.0.0, because v3.1.0 targets .NET Standard instead of the full .NET Framework (see #295).

In v3.0.0, it uses `Task.Factory.StartNew` to invoke `IEnumerator.MoveNext` asynchronously. In v3.1.0, the `IEnumerator.MoveNext` is invoked synchronously, in a blocking way. This negates all the benefits of `IAsyncEnumerable`, but that's a different question...

You're right that it makes no sense to use schedulers for `Task.FromResult`, since it returns a task that is already completed.

In my scenario, I use a custom task scheduler that queues the tasks to run on a specific "working" thread, instead of the .NET thread pool (which is a default behavior of `Task.Factory.StartNew` when you don't specify a scheduler). Others might want to use a custom scheduler, for example, to target a specific `SynchronizationContext`, to limit the concurrency level, to target the the I/O thread pool, etc.

**Comment by shiftkey** [comment]
cc @onovotny for feels on ☝️

**Comment by onovotny** [comment]
@krs500 I responded here...
https://github.com/Reactive-Extensions/Rx.NET/issues/295#issuecomment-261266468 Does that help?

**Comment by krs500** [comment]
Although `NETStandard.Library` is fully supported for `net45`, as you say, I can't afford shipping the whole `NETStandard.Library` along with my desktop app, especially when it is just a subset of the full .NET, from the API perspective. Why I can't reuse the .NET Framework that is already installed? But this is not the question that I'm asking.

As for the questions posted above, no, that doesn't help.

**Comment by onovotny** [comment]
Closing due to age. Please re-open based on the 4.0 preview behavior and functionality.
