### ISSUE TITLE
Intermittent test failure: ReactiveTests.Tests.ObservableTest.UsingAsync_Simple

### ISSUE THREAD

**Issue by onovotny** [dotnet/reactive#414]
It's sometimes failing

**Comment by akarnokd** [comment]
Is the `Assert.True(done)` failing? I'm not familiar with that particular `Using` overload but I'd guess the asynchronous setting of `done` may happen just a bit later when the main thread returns from consuming the blocking `ToEnumerable`.

Maybe instead of a `done` flag, a `CountdownEvent` could be used and awaited in the test thread for some hundred milliseconds?

**Comment by akarnokd** [comment]
Move to Milestone: vNext?
