### ISSUE TITLE
Consider the use of ValueTask<T> in async LINQ operators

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/reactive#430]
Right now, the prototype of C# 8.0 query operators for `IAsyncEnumerable<T>` introduces overloads such as:

```csharp
public static IAsyncEnumerable<T> Where<T>(this IAsyncEnumerable<T> source, Func<T, Task<bool>> predicate);
public static IAsyncEnumerable<R> Where<T, R>(this IAsyncEnumerable<T> source, Func<T, Task<R>> selector);
```

We should consider the pros and cons of using `ValueTask<T>` for the return type of these delegate arguments.

In addition, we should measure how much overhead the async overloads incur, and consider removing a lot of code duplication for the synchronous and asynchronous case, in favor of using `Task.FromResult(x)` or `new ValueTask<T>(x)` to convert the synchronous case into the asynchronous one.

**Comment by andriysavin** [comment]
I've just faced a scenario which I think is related. I'm enumerating files in Azure Files service directory, and the files are returned in batches (segments). I want to have an async enumerable around that, because to enumerate all files I'll have several async service calls. But the number of files in each batch is much bigger than number of batches (calls). Asynchronously iterating each file in a batch is a very expensive operation due to Task(s) allocation. It looks like ValueTask would be a nice solution for this, but obviously this should be a special implementation.

**Comment by bartdesmet** [comment]
Done in latest implementation of `System.Linq.Async`.
