### ISSUE TITLE
Catch Scheduler doesn't work with ScheduleAsync

### ISSUE THREAD

**Issue by StephenRobin** [dotnet/reactive#437]
When an exception is thrown by an action scheduled using Schedule it will always be caught by the Catch Scheduler.  When an exception is thrown by an action scheduled using some overloads of ScheduleAsync it will be swallowed internally and never reaches the Catch Scheduler.

We found this bug in production on 3.1.1.0.  I have reproduced it on master at v4.0.0-preview1 by adding the test below to ReactiveTests.Tests.SchedulerTest.

```
[Fact]
public void Catch_Builtin_Swallow_Async()
{
    var done = new ManualResetEvent(false);

    var swallow = Scheduler.Default.Catch<InvalidOperationException>(_ => { done.Set(); return true; });

    swallow.ScheduleAsync(async (s, t) =>
                        {
                            throw new InvalidOperationException();
                        });

    done.WaitOne();
}
```

My guess is this happens because an exception is thrown within the ContinueWith continuation and therefore is picked up by the TPL, see the InvokeAsync method in Scheduler.Async.cs.

**Comment by akarnokd** [comment]
`Catch` only activates if the scheduled `Action` throws, however, scheduling an async `Task` does not throw on the initiating thread and thus the `Catch`'s handler is never run. Catch would need to redefine `ScheduleAsync` in order to latch onto the inner task which I don't see how could happen since `Catch` returns an `IScheduler` and `ScheduleAsync` is an extension method.

**Comment by ts2do** [comment]
The exception could be propagated by scheduling a new action to the IScheduler in AsyncInvocation<>.Run which would simply rethrow t.Exception. Is there a problem with this approach?
