### ISSUE TITLE
WithLatestFrom: how does it even work?

### ISSUE THREAD

**Issue by kentcb** [dotnet/reactive#444]
There are already other issues/PRs open re `WithLatestFrom`, but nothing seems to be happening with them, and I'm not 100% sure they're exactly related to this. I must be misunderstanding how the operator works.

Consider this:

```C#
[Fact]
public void with_latest_from()
{
    var user = new BehaviorSubject<string>(null);
    var instanceId = new BehaviorSubject<string>(null);
    var executed = false;

    user
        .WithLatestFrom(
            instanceId,
            (_, __) => executed = true)
        .Subscribe();

    // uncommenting this makes test pass
    //user.OnNext("foo");

    // but not this
    //instanceId.OnNext("foo");

    Assert.True(executed);
}
```
My expectation was that `executed` would be `true` without needing to tick more values through either subject.

Am I misunderstanding the operator, or is it buggy?

**Comment by akarnokd** [comment]
The way `WithLatestFrom` is implemented in Rx.NET is that the main source is subscribed first, then the parameter source. Since the main source emits `null` immediately and without finding its pair from the other source (which is not yet subscribed to), the `resultSelector` function is not called. The operator caches only the latest value from this other source then on thus calling `instanceId.OnNext("foo")` will just replace this cached value but not trigger the `resultSelector` function. For that, the `user.OnNext` has to be called.

**Comment by kentcb** [comment]
@akarnokd thanks for confirming.

But is that really...expected? Shouldn't the source be published so that no values are lost? This seems really unintuitive to me. I can't think of any other operator that loses values from the source like this.

**Comment by akarnokd** [comment]
What is your use case? You may be trying to use the wrong operator.

 I consider `withLatestFrom` as a reconfigure operator: the main source is processed according to the latest configuration pushed through the other source but unlike `combineLatest`, a configuration change pushed should not trigger the reevaluation of the latest item from the main source.

**Comment by kentcb** [comment]
The use case is the `InvokeCommand` helper in ReactiveUI. It takes a source observable that dictates when a command should be invoked, but it needs to know whether the command is executable when the source ticks:
```C#
return @this
    .WithLatestFrom(command.CanExecute, (value, canExecute) => InvokeCommandInfo.From(command, canExecute, value))
    .Where(ii => ii.CanExecute)
    .SelectMany(ii => command.Execute(ii.Value).Catch(Observable<TResult>.Empty))
    .Subscribe();
```
So changes to `canExecute` ("configuration") should not re-execute the command. However, when `@this`  (the "main source") ticks, we always want to trigger the rest of the pipeline.

**Comment by kentcb** [comment]
Here is a working implementation that we were using with the old Rx 2.2.5, but I had hoped to remove it when moving to Rx 3:
```C#
public static IObservable<TResult> WithLatestFromFixed<TLeft, TRight, TResult>(
    this IObservable<TLeft> @this,
    IObservable<TRight> other,
    Func<TLeft, TRight, TResult> resultSelector) =>
    @this
        .Publish(
            os =>
                other
                    .Select(
                        a =>
                            os
                                .Select(b => resultSelector(b, a)))
                    .Switch());
```

**Comment by akarnokd** [comment]
That `invokeCommand` use case does sound like `withLatestFrom` should work, unless you have a default initial value in `@this` which gets dropped because the other is not subscribed in time. The publish-select-switch just reverses the order in which sources are subscribed because the lambda in publish gets executed and its results [subscribed to before](https://github.com/Reactive-Extensions/Rx.NET/blob/develop/Rx.NET/Source/src/System.Reactive/Linq/Observable/Multicast.cs#L51) the `@this` gets subscribed to.

**Comment by kentcb** [comment]
> unless you have a default initial value in @this which gets dropped because the other is not subscribed in time

Yes, this is the exact behavior I'm trying to get to the bottom. It seems counterintuitive to me for this value to be dropped, and apparently I'm not alone. See #152 for example.

**Comment by akarnokd** [comment]
Indeed. It seems you have two options: 
1) keep using the publish-select-switch operator or 
2) write a custom one based on the standard [`WithLatestFrom`](https://github.com/Reactive-Extensions/Rx.NET/blob/develop/Rx.NET/Source/src/System.Reactive/Linq/Observable/WithLatestFrom.cs).
3) Write a custom one from scratch.

The problem with 1) is the potential race and data loss because of how switch and publish may not atomically change state. The problem with 2) is the heavy use of internal infrastructure which may not be accessible outside. Option 3) isn't as hard as it may seem, I've written this operator a myself in C# some time ago.

**Comment by akarnokd** [comment]
Here is one implementation I quickly cobbled together: [Gist](https://gist.github.com/akarnokd/45e07786fa622d6893891d3afef955fc).
