### ISSUE TITLE
ChannelReader<T> Conversion

### ISSUE THREAD

**Issue by cecilphillip** [dotnet/reactive#472]
Re: https://github.com/aspnet/SignalR/pull/1890#issuecomment-379461743

Any chance a ChannelReader converter could be added to RxNet? Similar to the Task<T> interop?

**Comment by akarnokd** [comment]
It looks like `System.Threading.Channels` is something brand new and in [preview](https://www.nuget.org/packages/System.Threading.Channels/) so we can't depend on it and have a non-preview release. Also I'm not familiar with the splitting of the core assemblies but isn't this something that is not part of a standard dependency; i.e., just by creating a plain console app, I can use `Task` immediately but have to nuget channels into my project?

**Comment by Shammah** [comment]
Me and a colleague ran into the same 'problem'. While it's trivial to write a `AsChannelReader` observable extension as per https://github.com/aspnet/SignalR/blob/962ea25637a70c99ccbda2b47e3d682dd29da9ec/samples/SignalRSamples/ObservableExtensions.cs#L18-L31, a `AsObservable` requires a hot loop.

It kinda looked like this:

```
public static IObservable<T> ToObservable<T>(this ChannelReader<T> channel)
{
    return Observable.Create<T>(o =>
    {
        var cancel = new CancellationDisposable();
        Task.Run(async () =>
        {
            while (true)
            {
                o.OnNext(await channel.ReadAsync(cancel.Token));
            }
        });
        return cancel;
    });
}
```

This is obviously incomplete, but should get you on the right track.

**Comment by cecilphillip** [comment]
Is still in consideration ?

**Comment by bartdesmet** [comment]
Extensions for e.g. `ChannelReader` do make sense in the bigger Rx.NET offering, but not in the core `System.Reactive` assembly. Such extensions either belong in the product being extended with Rx support (by natively implementing `IObservable<T>` or other interface types, or by having `As` or `To` conversion operators as methods or extension methods), or a bridge assembly with a name akin to `System.Reactive.Foo` where `Foo` is reflective of the namespace where the functionality being bridged with is present (e.g. `Threading.Channels`).

It's an unfortunate precedent that functionality for Windows Forms and WPF was fused with the core `System.Reactive` assembly rather than being kept in its own assemblies. We should prefer a modular approach whenever possible.

This said, I'd be happy to review bridges like these, either as pull requests for new bridge assemblies here, or as pull requests in receptive target libraries, or as stand-alone GitHub projects that contribute to the Rx ecosystem.
