### ISSUE TITLE
Investigate skipped tests in Ix

### ISSUE THREAD

**Issue by onovotny** [dotnet/reactive#625]
Share4, Finally6.

**Comment by akarnokd** [comment]
I think `Share4` was disabled because `e1.Dispose` has no effect on the `IEnumerator` as it is implemented via a `yield return` state machine. I don't know if it is even possible or not.

This could be fixed via a manual state machine.

As for `Finally6`, the `Finally()` part does not run. I see 3 cases:

1) I don't know how long a cancellation token is supposed to be valid for a `MoveNext` so the test might be too fast completing the first task such that `Cancel` has no effect.
2) The `token` could be reacted to until the next `MoveNext` is invoked thus even if a value is ready, cancel still propagates.
3) `Finally` could be registering with the token which it doesn't do currently.

**Comment by onovotny** [comment]
Thanks @akarnokd.

I agree that's the cause for `Share4`. In the interest of correctness, it's probably worth turning this into a state machine.

Not sure what the right thing is yet for `Finally6`

**Comment by akarnokd** [comment]
I'll post a PR shortly for the two.
