### ISSUE TITLE
GroupBy and ObserveOn race condition causes loss of elements

### ISSUE THREAD

**Issue by glen-nicol** [dotnet/reactive#841]
I am seeing similar behavior related to #411 except I am not sending notifications in parallel. The GroupBy operator uses a Subject<T> which is a hot observable which is the source of my problem.

```csharp

stream.GroupBy(e => e.Key)
    // With the ObserveOn after the GroupBy I loose the first element because the 
    // inner subscription created by SelectMany is made on the UI thread after the 
    // GroupBy has posted its onNext to the Subject<T> it uses internally.
    .ObserveOn(ViewModelSchedulers.UIThread) 
    .SelectMany(groupedStream => Observable.Defer(() => 
        {Do some one time per group UI setup} 
        return groupedStream.Do({Use UI setup}))
```

I was able to workaround it by moving the ObserveOn operator higher so that the GroupBy is applied on the UIThread but that is contrary to the guidelines that suggest to apply ObserveOn and SubscribeOn as late as possible.

I was hesitant to create an issue for this because I don't see an easy way to fix the problem. Using a BehaviorSubject<T> would probably fix my issue but still wouldn't fix the problem if multiple elements get posted before the UI thread was able to run and subscribe. Maybe if we had a buffer until subscribe subject it would work.

Regardless, I did want to make sure it was documented as a known problem with these two operators used in conjunction.

**Comment by akarnokd** [comment]
Any delay in consuming a group may cause lost items as the groups are practically plain `Subject`s. `BehaviorSubject` wouldn't help you beyond the last item seen, but then more items could have been dropped already. There is an [`UnicastSubject`](https://github.com/akarnokd/reactive-extensions#unicastsubject) for Rx.NET that buffers until there is an actual observer, but you'd still have to prestart the group:

```cs
stream.GroupBy(e => e.Key)
.Select(g => {
    var us = new UnicastSubject<T>();
    g.Subscribe(us);
    return us;
});

**Comment by glen-nicol** [comment]
Is there a reason GroupBy doesn't use a UnicastSubject internally? And you're right more could be lost depending on the timing. In my particular case I only have one element to loose per group which is why a BehaviorSubject would work.

**Comment by akarnokd** [comment]
`UnicastSubject`, and specifically the behavior it represents, afaik was never part of the Rx.NET vocabulary. [We knew about the issue in RxJava](https://github.com/ReactiveX/RxJava/issues/844) for years now. Probably the workaround has been to use `ReplaySubject`, like my example above, at the cost of longer item retention.

**Comment by glen-nicol** [comment]
If I read the diff correctly on the PR for the Java issue they just replaced their subject with an equivalent to UnicastSubject. Can that be done on the Rx.Net side or would that be a breaking change?

**Comment by glen-nicol** [comment]
Are you saying there are overloads with the subjectfactory as a parameter? I didn't see/notice those as an available signature. Or is the "built here" supposed to be a link referring to something other than Rx.Net?

**Comment by bartdesmet** [comment]
> Are you saying there are overloads with the subjectfactory as a parameter? I didn't see/notice those as an available signature. Or is the "built here" supposed to be a link referring to something other than Rx.Net?

Sorry for the confusion. Rx does not have such overloads. I was referring to the internal Reactor service I've been building in Bing/Azure after my time on the Rx library, where we do have the notion of factories for hot resources:

- Subject factories create subjects (hot due to keeping a list of subscribers).
- Observer factories create observers (hot due to state about the Rx grammar, e.g. completed/faulted).
- Subscription factories create subscriptions (hot for obvious reasons).

In this new "standard model of reactive", observables are merely subscription factories that happen to be parameterized on observers (or factories thereof).

For proper Rx, the notion of subject factories could be imported for operators such as GroupBy and Window which construct subjects under the hood, and it's impossible to influence the choice of subject type today. In such a world, these operators would take `Func<ISubject<T>>` or similar methods on overloads, the default being `() => new Subject<T>()`. This also allows to intercept `On*`, `Subscribe`, and `Dispose` calls on these subjects.

This in turn could be used to assert against incorrect usage, i.e. where a `Subscribe` call happens after any `On*` call, which is indicative of not subscribing to the group or window immediately (e.g. due to a time gap introduced by `ObserveOn`). In the aforementioned Reactor system, we have such a notion called "sealing" where any subject emitted by an operator has to be used in the synchronous code path emitting the subject to the downstream observer (in order to avoid tricky lifetime issues when it comes to knowing when a subject is no longer "alive" and can be dropped from persisted checkpoint state, and to spot hard to find race conditions as the one mentioned here).

> If I read the diff correctly on the PR for the Java issue they just replaced their subject with an equivalent to UnicastSubject. Can that be done on the Rx.Net side or would that be a breaking change?

This would be a breaking change, so no, we can't do that. But the parameterization on subject factories would be okay to do (and as a bonus exercise, one could thinker with the duality of this in Ix).
