### ISSUE TITLE
strange behavior of WithLatestFrom in case of high load

### ISSUE THREAD

**Issue by tvvister** [dotnet/reactive#847]
Undetermined result of program output has occuried:
try to launch programm several times consequentially.
My tests:
output #1-5:
	{ RawData = { GenIndex = **_0_**, PredicateValue = True }, PredData = { GenIndex = 0, PredicateValue = True } }
	{ RawData = { GenIndex = 1, PredicateValue = False }, PredData = { GenIndex = 0, PredicateValue = True } }
	{ RawData = { GenIndex = 2, PredicateValue = False }, PredData = { GenIndex = 0, PredicateValue = True } }
	.....
	
output #6:
	{ RawData = { GenIndex = **_6_**, PredicateValue = False }, PredData = { GenIndex = 4, PredicateValue = True } }
	{ RawData = { GenIndex = 7, PredicateValue = False }, PredData = { GenIndex = 4, PredicateValue = True } }
	{ RawData = { GenIndex = 8, PredicateValue = True }, PredData = { GenIndex = 8, PredicateValue = True } }
	.....
	
I've observed that code skips some elements from result. It may be effect related with race condition. But it seems like error.

class Program
    {
        private static IDisposable _subscription;

        static void Main(string[] args)
        {
            var sourceScheduler = new NewThreadScheduler();

            var source = Observable.Interval(TimeSpan.FromSeconds(0.1), sourceScheduler)
                .Select(genIndex => new { GenIndex = genIndex, PredicateValue = genIndex % 4 == 0 })
                .Publish()
                .RefCount();

            StartHighLoadTask(); // Very heavy problem !!!

            var predicateValueTrueStream = source
                .Where(x => x.PredicateValue);

            var resultStream = source
                .WithLatestFrom(predicateValueTrueStream, (rawData, predicateData) => new { RawData = rawData,  PredData = predicateData } );

            _subscription = resultStream
                .Subscribe(Console.WriteLine);

            Console.ReadLine();
        }

        private static void StartHighLoadTask()
        {
            Task.Run(() =>
            {
                var results = Enumerable.Range(0, 16)
                    .AsParallel()
                    .Select(x =>
                    {
                        BusyWait(10000);
                        return x;
                    }).ToArray();
            });
        }

        public static void BusyWait(int milliseconds)
        {
            var sw = Stopwatch.StartNew();

            while (sw.ElapsedMilliseconds < milliseconds)
                Thread.SpinWait(1000);
        }
    }
}

**Comment by akarnokd** [comment]
What Rx.NET version are you using?

**Comment by tvvister** [comment]
4.1.2.343

**Comment by tvvister** [comment]
But I has cheched on version 4.2.0-preview.55. Result is same

**Comment by akarnokd** [comment]
I've run your program on my i7 4790 CPU (4/8) and it always started at 0, even if I reduced the interval to 1 milliseconds There shouldn't be any dataloss as `publish` notifies `predicateValueTrueStream` first, then `source` synchronously so there should be always a latest to combine with.

**Comment by tvvister** [comment]
I've run on my i5-2500 CPU 3.30GHz 3.30GHz. So dataloss has occuried. Could you try to make launch with varying parameter "taskCount" from 16, 32 ,64, 256, ... ? I think you can find critical condition. If you set parameter to "1"  value, result will start with GenIndex = 0. 
Program for experiments:
class Program
    {
        private static IDisposable _subscription;

        static void Main(string[] args)
        {
            var sourceScheduler = new NewThreadScheduler();
            int taskCount = 16;

            var source = Observable.Interval(TimeSpan.FromSeconds(0.1), sourceScheduler)
                .Select(genIndex => new { GenIndex = genIndex, PredicateValue = genIndex % 4 == 0 })
                .Publish()
                .RefCount();

            StartHighLoadTask(taskCount); // Very heavy problem !!!

            var predicateValueTrueStream = source
                .Where(x => x.PredicateValue);

            var resultStream = source
                .WithLatestFrom(predicateValueTrueStream, (rawData, predicateData) => new { RawData = rawData,  PredData = predicateData } );

            _subscription = resultStream
                .Subscribe(Console.WriteLine);

            Console.ReadLine();
        }

        private static void StartHighLoadTask(int taskCount)
        {
            foreach (var taskIndex in Enumerable.Range(0, taskCount))
            {
                Task.Factory.StartNew(() =>
                {
                    BusyWait(10000);
                }, TaskCreationOptions.LongRunning);
            }
        }

        public static void BusyWait(int milliseconds)
        {
            var sw = Stopwatch.StartNew();

            while (sw.ElapsedMilliseconds < milliseconds)
                Thread.SpinWait(1000);
        }
    }

**Comment by danielcweber** [comment]
It's due to RefCount subscribing to the `Interval`-observable the moment that `WithLatestFrom` subscribes to `predicateValueTrueStream`. In some cases, it'll observe a value before it had a chance to subscribe to `source` and this is when values will be missed. You can workaround this by not using `RefCount`, but calling `IConnectableObservable.Connect` manually after you set everything up (i.e. after `resultStream.Subscribe`).

**Comment by bartdesmet** [comment]
@danielcweber's answer is spot on; this is by design. One should always be very wary of these `.Publish().RefCount()` combos because they hide a lot of imperative machinery under the hood.

This effectively creates a connect/disconnect "tap" that will be toggled each and every time the reference count goes between `0` and `1` (in either direction), so you have a "tepid" source in here that behaves as if it's cold (when reference count is at `0`, it being idle and not producing values), but depending on the timing may be "hot" (actively running and producing values). Whenever something is not purely "cold", you should assume it's hot and multiple subscribers trying to "tune in" to the source have no guarantee to subscribe at exactly the same time. E.g. `hot.Zip(hot, (l, r) => l == r)` is not guaranteed to produce a sequence of `true`, because the two subscriptions to `hot` are not atomic and time will pass in between creating those subscriptions.

When anything is hot and you want all subscribers to the thing to see exactly the same event sequences, you need phasing to create the subscription and pour open the "tap" at the top after everything has been set up. The way to do that is indeed by just using `Publish`, and call `Connect` all the way at the bottom:

```csharp
    static void Main()
    {
        // Keep it cold until you've created the entire query (no RefCount)
        var source = Observable.Interval(TimeSpan.FromSeconds(0.1), new NewThreadScheduler())
            .Select(genIndex => new { GenIndex = genIndex, PredicateValue = genIndex % 4 == 0 })
            .Publish();

        // Compose as much as you want here (use source many times)
        var predicateValueTrueStream = source.Where(x => x.PredicateValue);
        var resultStream = source
            .WithLatestFrom(predicateValueTrueStream, (rawData, predicateData) => new { RawData = rawData,  PredData = predicateData } );

        // Subscription to an arctic cold source; the Interval will not be started at all
        IDisposable subscription = resultStream.Subscribe(Console.WriteLine);

        // Now open the tap at the top
        IDisposable connection = source.Connect();

        // Disposing the whole thing now means closing the tap, and disposing the subscription
       _subscription = new CompositeDisposable(connection, subscription);

        Console.ReadLine();
    }
```

FWIW, the Reactor service built here internally in Bing/Azure uses a variant of Rx where `Subscribe/Dispose` is merely `Attach/Detach` and is accompanied by a mechanism to `Start/Stop` the computation, thus adding phasing to distinguish between setting up the event processing topology and starting the flow of events. Rx does not have this in a pervasive manner thoughout the library; instead, it has `IConnectableObservable<T>` and you have to deal with `Connect` directly, in the right place.
