### ISSUE TITLE
Is there an reactive ObservableCollection?

### ISSUE THREAD

**Issue by msedi** [dotnet/reactive#862]
I'm always struggling with the ObservableCollection which is nice, but has a lot of drawbacks regarding concurrency, batch updates, any many more things. At first I thought using reactive extensions is easy but then I found that it isn't and was digging through the web if someone has already solved it.

I found this (https://github.com/RolandPheasant/DynamicData) and another solution, but it would be awesome if there is something that comes out of the box, like System.Reactive.Collections.

Have you thought about this or is there something I missed?

**Comment by danielcweber** [comment]
I am the author of [ExRam.ReactiveCollections](https://github.com/ExRam/ExRam.ReactiveCollections) ([Nuget](https://www.nuget.org/packages/ExRam.ReactiveCollections)). It bridges Rx with Immutable Collections to abstract change in lists (or dictionaries, sorted lists etc.) as sequences of immutable collections. There is not a lot of documentation but you might get an idea from the unit tests.

**Comment by msedi** [comment]
@danielcweber. Thanks Daniel I had a look and it looks very nice. Nevertheless the DynamicData seems to me that it covers more cases that are an essential requirement for me, like aggregate and join multiple "ObservableCollections" into one and also other cases. Have you seen it, what do you thin about it?

**Comment by danielcweber** [comment]
Seems a very extensive library too. On a first sight, I don't know how it deals with concurrency (reading and writing at the same time, while expecting lists to be consistent). Concurrency was the major incentive for ReactiveCollections, thus the use of immutable collections.

**Comment by msedi** [comment]
@danielcweber. Yes, this is also my concern, the library is pretty big and I need to dig in a little. If possible I can keep you up to date. It's a bit sad though that the conventional Rx has no support for this.

**Comment by worldbeater** [comment]
Reactive extensions are themselves collections that change over time and you can transform them as you wish using numerous LINQ-style operators. Integrating Reactive Extensions with `System.Collections.ObjectModel.ObservableCollection<T>` is probably out of scope of this project. 

But I'd recommend you taking a look at [ReactiveUI](https://reactiveui.net/) — a fully-featured functional reactive cross-platform MVVM framework for .NET. They used to have their own `ObservableCollection<T>` reactive implementation, named `ReactiveList<T>` (see [docs](https://reactiveui.net/docs/handbook/obsolete/collections/reactive-list)), although it's now marked as obsolete. The recommended approach now is to use [DynamicData](https://reactiveui.net/docs/handbook/collections/) for mutable collections and [ObservableAsPropertyHelper](https://reactiveui.net/docs/handbook/oaph/) for immutable ones. Hope this helps :raised_hands:

**Comment by bartdesmet** [comment]
I agree with @worldbeater's assessment of this being outside the scope of the core Rx libraries. The unfortunate thing about `ObservableCollection<T>` is the `Observable` suffix, which makes it look more Rx-like that it really is.

Bridges with this type belong is extensions on top of Rx, similar to the original design of Rx where extensions for Windows Forms and WPF were kept in separate pay-for-play assemblies. The core Rx functionality for `IObservable<T>` and `IScheduler` base classes provide the building blocks to create these bridge assemblies higher up (again, in the original design, one would just need to depend on `System.Reactive.Core` to build these without sucking in the `System.Reactive.Linq` layer).

The mere fact there are a few of these adapters already shows there's no single design that fits all requirements, especially due to the opinionated nature of UI frameworks around scheduling and thread-affinity, even though types like `ObservableCollection<T>` can also be used in a different context. Good examples of libraries that bridge between collections and Rx notions are mentioned on this thread, including ReactiveUI and ReactiveCollections.
