### ISSUE TITLE
CombineLatest/Zip Completion Behavior

### ISSUE THREAD

**Issue by ts2do** [dotnet/reactive#885]
I've been looking over the implementation of CombineLatest & Zip and was wondering if anyone knew why the operators defer completion in certain circumstances.
Specifically:
CombineLatest doesn't complete immediately when the first source with no value completes. CombineLatest completes when all but one of the sources are complete and the active source provides a value; this behavior would appear to have been copied from Zip and should probably not do this.
Zip doesn't complete immediately when 1) a source with no queued values completes or 2) a source provides a value which empties the queue of a completed source.

**Comment by bartdesmet** [comment]
The described behavior of `CombineLatest` is by design. One of the design principles of Rx has been to provide determinism for operators with multiple sources, with regards to termination behavior and `OnError` in particular. We also try hard not to drop `OnError` messages due to abandoning subscriptions (unless an `OnError` is in flight itself, i.e. we don't use `AggregateException` or await other erroneous outputs that would cause delay of `OnError` propagation), and `OnError` propagates as fast as possible (e.g. not queued in `Delay`).

In this particular case, consider `Throw<int>(ex).CombineLatest(Empty<int>(), f)` versus `Empty<int>().CombineLatest(Throw<int>(ex), f)`. We felt strongly that both queries should deterministically produce `OnError`, thus not depending on order or even timing of both sources (say both sources use schedulers that introduce threading). As a result, a single source cannot unilaterally decide on successful `OnCompleted` termination of `CombineLatest`; it has to await the outcome of other concurrent sources that may produce an `OnError`.

**Comment by ts2do** [comment]
Alright. Thanks for the clarification.
